public/css/admin.css, public/js/admin.js, templates/main/admin.html.ep, templates/ng-templates/admin_nav.html.ep, templates/ng-templates/list_machines.html.ep
=> 107c refactor

lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/VM/KVM.pm, sql/mysql/Makefile, sql/mysql/base_xml.sql, sql/sqlite/base_xml.sql, t/etc/sql.conf, t/kvm/60_dom_settings.t, t/kvm/a20_xml.t, t/vm/20_base.t
This fixes frankiejol/ravada#142
=> [#142] Store and retrieve XML definition for KVM bases

lib/Ravada/Auth/SQL.pm, lib/Ravada/I18N/ca.po, lib/Ravada/I18N/en.po, lib/Ravada/I18N/es.po, rvd_front.pl, templates/bootstrap/navigation.html.ep, templates/bootstrap/user_settings.html.ep
It seems that the error messages via the errors function cannot translate, so the warning messages are always in english. Except that, everything about the settings page should be working properly.
=> User settings

templates/main/admin_machines.html.ep
=> #203 look and feel status column machine list improved

devel-docs/custom_login.md, etc/rvd_front.conf.example, rvd_front.pl
Add new parameter in rvd_front.conf
Add directories for: CSS, JS, IMG
Add directory for custom_template
Add documentation for custom login
=> Add custom login

lib/Ravada.pm, templates/main/settings_machine.html.ep
Keep selected tab on page refresh
Fixed missing rows when upgrading
=> 260 settings

public/js/ravada.js, templates/main/list_bases2.html.ep
=> Revert "[#328] Button hidden when theres no private machines"

lib/Ravada/I18N/id.po
Indonesia Translation
Add indonesia translation
=> Add Indonesia translation

lib/Ravada/I18N/en.po
There are some msgid repeated in en.po
Delete repeated msgid and documented how to check.
This problem is often repeated.
https://github.com/UPC/ravada/issues/367
=> 367 Remove msgid repeated

lib/Ravada/VM/KVM.pm
=> [#383] defines pool, then creates

rvd_front.pl
=> [#386] Bug solved

public/css/admin.css, templates/ng-templates/new_machine_template.html.ep
Turned Disk, Swap and Ram Sizes into sliders.
It conveys the information to the user (the max and min Disk, Swap and Ram allowed when creating a machine).
=> 274 sliders

lib/Ravada/I18N/fr.po
Rewording the french descriptions to be more clear to native speakers. Tried to keep a consistent voice in the wording of the strings. Modified some words to be more in line with common French technical jargon, such as "Déconnecter" instead of "Sortir".
Addressing issue #398
=> Updated french translation

lib/Ravada/I18N/ca.po, lib/Ravada/I18N/en.po, lib/Ravada/I18N/es.po
Updated es.po and ca.po comparing them with en.po.
Once the merge is done, don't erase the branch, in order for other contributors to update the remaining languages.
=> 398 update languages

lib/Ravada/Front.pm, lib/Ravada/VM/KVM.pm, public/js/admin.js, public/js/ravada.js, rvd_front.pl
First batch of security checks
=> 405 access

lib/Ravada/I18N/pt.po
Adds Portuguese translations
I've added a pt.po file with Portuguese messages
A contribution for #398
=> Adds Portuguese translations

lib/Ravada/I18N/en.po
I've reviewed and made some changes to the en.po file
Adressing the issue #411
=> Updated English translation

lib/Ravada/I18N/en.po
=> Fix Hybernate to Hibernate

lib/Ravada/I18N/en.po
Fixes minor grammatical errors and issues #411.
=> UPDATE en.po (Issue #411)

lib/Ravada/I18N/en.po
=> Improved English

lib/Ravada/I18N/hi.po
Added a new translation file `hi.po` for English to Hindi translations.
Being an Indian, Hindi is my mother tongue. I have tried my best to make the translations precise and meaningful to Hindi speaking users.
Fixing issue https://github.com/UPC/ravada/issues/418
=> ADD - Hindi language translations

templates/main/vm_copy.html.ep, templates/main/vm_description.html.ep, templates/main/vm_drivers.html.ep, templates/main/vm_options.html.ep, templates/main/vm_remove.html.ep, templates/main/vm_rename.html.ep
I have added cancel buttons to all the machine setting forms.
=> [#331]Cancel buttons added to all the machine setting forms.

lib/Ravada/I18N/de.po
=> Adding german translation

lib/Ravada/I18N/de.po
Correct the already existing german translations to improve quality
=> Correct german translations

templates/main/vm_description.html.ep
Fix encoding in text-area
Add ISO-8859-1 charset
Accents and other chars not show properly
https://github.com/UPC/ravada/issues/430
=> [#430] Fix encoding charset

lib/Ravada/I18N/de.po, lib/Ravada/I18N/en.po
Removed duplicates of msgids both in the German and English language file.
After creating a german translation, i wanted to clean up some of the translations before contributing more localizations in the template files. Also comment https://github.com/UPC/ravada/issues/398#issuecomment-336995428 by fv3rdugo asks for checking which apparently was not done for both languages.
Refers to issue https://github.com/UPC/ravada/issues/398.
=> [#398] remove repeated msgid

lib/Ravada/I18N/pt.po
Fixed a couple of typos and changed some translations to the way I see more fitting.
Text changes.
=> Fixed PT translation.

lib/Ravada/I18N/en.po
I updated the English translations based on comments I had made on another PR.
This is further refinement of the English translations. See discussion in #411 for more details.
=> Review English Translation

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Front.pm, lib/Ravada/VM/KVM.pm, public/js/ravada.js, t/front/10_load.t, t/kvm/62_images.t, t/lib/Test/Ravada.pm, templates/main/settings_machine_tabs_head.html.ep, templates/main/vm_copy.html.ep, templates/main/vm_graphics.html.ep, templates/main/vm_rename.html.ep
=> 443 settings

templates/ng-templates/new_machine_template.html.ep
=> 425 help buttons new machine

etc/xml/jessie-i386.xml, etc/xml/trusty-amd64.xml, etc/xml/trusty-i386.xml, etc/xml/win10.xml, etc/xml/win7pro.xml, etc/xml/win8.1.xml, etc/xml/windows_10.xml, etc/xml/windows_12.xml, etc/xml/windows_7.xml, etc/xml/windows_8.xml, etc/xml/windows_xp.xml, etc/xml/zesty-amd64.xml
Now all xml files has graphics params recommended.
Change IPs to 127.0.0.1
=> [#473] Fix all xml with graphics params

etc/xml/dsl-i386.xml, etc/xml/jessie-amd64.xml, etc/xml/jessie-i386.xml, etc/xml/trusty-amd64.xml, etc/xml/trusty-i386.xml, etc/xml/windows_8.xml, etc/xml/xenial-i386.xml, etc/xml/xenial64-amd64.xml, etc/xml/yakkety64-amd64.xml, etc/xml/zesty-amd64.xml
Now all the templates has cut & paste configuration.
https://github.com/UPC/ravada/issues/476
=> [#476] Add xml lines to c&p

t/request/20_download_local.t, templates/main/admin_machines.html.ep, templates/main/list_bases2.html.ep
=> 320 volatile

lib/Ravada/I18N/jp.po, templates/bootstrap/user_settings.html.ep
=> Japanese translation

lib/Ravada.pm, lib/Ravada/VM/KVM.pm, sql/data/insert_iso_images.sql, t/lib/Test/Ravada.pm, t/request/20_download_local.t, t/user/20_grants.t, t/vm/z_101.t
Fix Debian and all other future downloads using regexpes in urls
=> 500 debian

lib/Ravada/I18N/ca.po, lib/Ravada/I18N/es.po, lib/Ravada/I18N/fa.po, lib/Ravada/I18N/fr.po, lib/Ravada/I18N/gl.po, lib/Ravada/I18N/hi.po, lib/Ravada/I18N/id.po, rvd_front.pl, templates/main/vm_copy.html.ep, templates/main/vm_drivers.html.ep, templates/main/vm_remove.html.ep, templates/main/vm_rename.html.ep
=> 452 addotherlanguagetoeachlanguage

lib/Ravada/Domain.pm, lib/Ravada/VM.pm, t/lib/Test/Ravada.pm
First try loading Rex on runtime
=> [#531] require Rex when needed

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Front/Domain.pm, lib/Ravada/VM.pm, lib/Ravada/VM/KVM.pm, t/front/20_create_domain.t, t/kvm/12_vm_kvm.t, t/request/40_base.t, t/vm/10_domain.t
=> 533 remove

lib/Ravada.pm, rvd_front.pl, templates/main/vm_copy.html.ep, templates/main/vm_drivers.html.ep, templates/main/vm_remove.html.ep, templates/main/vm_rename.html.ep
=> [#485] machineremovepage

templates/ng-templates/new_user.html.ep
Username can only contain words, numbers, dashes, dots and underscores
Now it allows you to include numbers in a new user and be consistent with the message
=> 524 register

bin/rvd_back.pl, lib/Ravada.pm, lib/Ravada/VM.pm, t/vm/r10_remote.t
=> 543 remote keys

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/Void.pm, lib/Ravada/Request.pm, lib/Ravada/VM.pm, lib/Ravada/VM/Void.pm, t/kvm/n10_nodes.t, t/lib/Test/Ravada.pm
=> 545 active

templates/bootstrap/scripts.html.ep, templates/main/run.html.ep, templates/main/vm_description.html.ep
in the text area of the description tab there's now an edit bar that allows you to enrich the text, add images, etc.
It allows to offer rich information to the user. 
We have added it thanks to [NicEdit](http://nicedit.com/) Javascript.
=> [#562] Add rich text editing in description tab

lib/Ravada.pm, public/js/admin.js, sql/data/insert_iso_images.sql, sql/mysql/iso_images.sql, templates/ng-templates/new_machine_template.html.ep
=> 447 min disk

lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, t/kvm/71_description_clones.t, t/vm/20_base.t, t/vm/40_volumes.t
=> [#554] base swap

lib/Ravada/VM.pm, t/vm/n10_nat.t, t/vm/n20_name.t
=> [#571] ip name

t/front/20_create_domain.t, t/vm/10_domain.t
=> [#575] [test] internal id on active domains

lib/Ravada/Domain.pm, lib/Ravada/Front.pm, t/front/20_create_domain.t, t/front/40_list_domains.t
=> [#575] update the internal id on domain startup

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Request.pm, t/kvm/n10_nodes.t, t/lib/Test/Ravada.pm
Remote nodes improved, it needs some usage testing now
=> 547 remote

etc/rvd_front.conf.example, lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Domain/Void.pm, lib/Ravada/Front.pm, lib/Ravada/Request.pm, public/js/admin.js, rvd_front.pl, t/vm/a10_autostart.t, templates/main/admin_machines.html.ep
=> 589 autostart

sql/data/insert_iso_images.sql
=> [#596] fetch md5sums from the same URL as the ISO

etc/rvd_front.conf.example, rvd_front.pl, templates/bootstrap/navigation.html.ep, templates/bootstrap/scripts.html.ep, templates/main/settings_machine_tabs_head.html.ep, templates/main/vm_monitoring.html.ep
Server monitoring support
Monitoring server page for admin role
Monitoring VMs
Documentation my-netdata.io server installation
Add option to rvd_front.conf for enabled
=> 567 netdata

etc/rvd_front.conf.example, rvd_front.pl, templates/bootstrap/user_settings.html.ep, templates/main/about.html.ep, templates/main/admin_machines.html.ep, templates/main/admin_messages.html.ep, templates/main/admin_users.html.ep, templates/main/list_bases.html.ep, templates/main/list_bases2.html.ep, templates/main/new_machine.html.ep, templates/main/requirements.html.ep, templates/main/settings.html.ep
=> [#559]I have added the option to customize the footer

lib/Ravada/Domain.pm, t/lib/Test/Ravada.pm, t/vm/90_fw.t, t/vm/n20_name.t
cleans iptables for a domain before starting
=> 597 iptables

t/vm/n10_nat.t
=> [#597] [test] properly test anywhere for nat

lib/Ravada/Domain.pm, t/vm/90_fw.t
=> [#597] iptables

lib/Ravada/Domain.pm, t/vm/90_fw.t
=> [#597] Add host ip when allowing localhost

rvd_front.pl, templates/main/vm_copy.html.ep, templates/main/vm_rename.html.ep, templates/ng-templates/new_machine_template.html.ep
Allow alphabetic, numbers, dashes and underscores in Machine names
=> virtual machine name restrictions changed

etc/rvd_front.conf.example, lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Domain/Void.pm, lib/Ravada/Front.pm, lib/Ravada/Front/Domain.pm, lib/Ravada/Request.pm, public/js/admin.js, rvd_front.pl, t/vm/a10_autostart.t, templates/main/admin_machines.html.ep
autostart features for master branch
=> 589 autostart 2

templates/main/requirements.html.ep
Fix class name for new fa-icons awesome version 5
=> [#620] Update class name

etc/rvd_front.conf.example
Document hidden options in rvd_front.conf.example
=> [#616] hidden options

README.md, bin/rvd_back.pl, lib/Ravada.pm, lib/Ravada/Front.pm, lib/Ravada/VM.pm, lib/Ravada/VM/KVM.pm, lib/Ravada/VM/Void.pm, t/front/40_list_domains.t
=> 626 refresh

lib/Ravada/Auth/SQL.pm, rvd_front.pl, t/55_freemem.t, t/user/20_grants.t, templates/main/admin_machines.html.ep, templates/ng-templates/new_machine.html.ep
=> [#635] grant create frontend

lib/Ravada/Domain.pm, lib/Ravada/VM.pm, t/kvm/n10_nodes.t, t/kvm/n20_nodes_hibernate.t, t/lib/Test/Ravada.pm
=> [#583] sync back

bin/rvd_back.pl, lib/Ravada.pm
=> 641 defunct

docs/docs/spice.reg
=> [#631] Changed version number in spice.reg file

templates/main/start.html.ep
=> footer included instead of hardcoded

docs/docs/INSTALL.rst, docs/docs/INSTALL_Fedora.rst, docs/index.rst
Documentation for Fedora installation.
=> [#448] fedora

bin/rvd_back.pl, lib/Ravada/Auth/LDAP.pm, t/65_user_ldap.t
Fixes some problems with LDAP bind
=> [#649] ldap

docs/docs/INSTALL.rst, docs/docs/INSTALL_Fedora.rst
=> [doc] Sugested changes on Fedora install

docs/docs/INSTALL_Script.rst, docs/docs/res/ravada_installer.sh
=> fix link in docs + ravada_latest.deb in script

lib/Ravada/Auth/LDAP.pm
=> [#649] retry if LDAP server returns error

rvd_front.pl, templates/bootstrap/scripts.html.ep, templates/main/settings_machine_tabs_head.html.ep
Netdata code to release 0.2.15
=> [#567] netdata

public/js/admin.js, templates/main/admin_machines.html.ep
https://github.com/UPC/ravada/issues/617
=> [#617] Refresh Btn

etc/xml/jessie-i386.xml, lib/Ravada.pm, t/vm/97_isos.t
Fixes jessie 32 bits was using 64 bits XML
=> [#670 usbctrl]

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Front.pm, lib/Ravada/Front/Domain.pm, lib/Ravada/Utils.pm, lib/Ravada/VM.pm, lib/Ravada/VM/KVM.pm, t/front/30_show_domain.t, t/lib/Test/Ravada.pm, t/vm/v10_volatile.t, t/vm/v20_volatile_clones.t
Backend side of volatile clones done
=> 628 volatile

rvd_front.pl
Change the error message that appears when you try to start a removed machine.
https://github.com/UPC/ravada/issues/485
=> 485 fixremovemachine

lib/Ravada/Auth/SQL.pm, lib/Ravada/Front.pm, rvd_front.pl, t/user/20_grants.t, templates/main/settings_machine_tabs_head.html.ep
=> 606 remove clone all

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/VM/KVM.pm, sql/mysql/domains_kvm.sql, sql/mysql/domains_void.sql, sql/sqlite/domains_kvm.sql, sql/sqlite/domains_void.sql, t/vm/v10_volatile.t
=> fix:  volatile machines files are removed

lib/Ravada/Domain.pm, lib/Ravada/Domain/Void.pm, lib/Ravada/Request.pm, t/kvm/n10_nodes.t
=> feat(backend): migrate back

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Front.pm, lib/Ravada/Front/Domain.pm, templates/main/admin_machines.html.ep
The remote client connection status can be available from the virtual machine.
At the frontend it shows disconnect instead of the IP at the machine list.
=> feat: show remote client connection status

t/lib/Test/Ravada.pm
=> test: remove old volumes from multiple storage pools

lib/Ravada/I18N/ca.po, lib/Ravada/I18N/de.po, lib/Ravada/I18N/en.po, lib/Ravada/I18N/es.po, lib/Ravada/I18N/fa.po, lib/Ravada/I18N/fr.po, lib/Ravada/I18N/gl.po, lib/Ravada/I18N/hi.po, lib/Ravada/I18N/id.po, lib/Ravada/I18N/jp.po, lib/Ravada/I18N/pt.po, t/90_pos.t, templates/bootstrap/new_user.html.ep, templates/main/admin_machines.html.ep, templates/main/list_bases2.html.ep, templates/main/settings_machine_tabs_head.html.ep, templates/main/vm_graphics.html.ep, templates/main/vm_remove.html.ep, templates/ng-templates/new_machine_template.html.ep, templates/ng-templates/new_user.html.ep
All the tests passed
- Update msgid strings
- Fix inconsistencies
- Now transifex use this en.po
=> [#646] fix(locales)

bin/rvd_back.pl, lib/Ravada.pm
=> feat(cli): manage disconnected machines

public/js/ravada.js
=> fix(view_machine): only copy if there is textarea

lib/Ravada.pm, lib/Ravada/Auth/SQL.pm, rvd_front.pl, sql/data/insert_grant_types.sql, sql/mysql/grant_types.sql, sql/sqlite/grant_types.sql, t/front/60_ldap.t, t/lib/Test/Ravada.pm, t/user/20_grants.t, templates/main/admin_machines.html.ep, templates/main/list_bases2.html.ep, templates/main/settings_machine_tabs_head.html.ep
This also sets the permissions that have been
implemented so far. Those must be enabled at
the sub _enable_grants at Ravada.pm
@joelalju, this when all the grants are implemented
it should be added there.
issue #698
=> feat(grants): enable or disable grant types

lib/Ravada/Front.pm
https://github.com/UPC/ravada/issues/611
=> [#611]Sort ISOs by name

docs/docs/INSTALL.rst, docs/docs/production.rst, docs/docs/recomendations.rst, docs/index.rst
Documentation is easy to mantain in the latest LTS version of Ubuntu.
Asked by @frankiejol
=> Updated to only support Ubuntu 18 and refactor documentation

Makefile.PL, lib/Ravada/Domain.pm, t/front/60_ldap.t, t/vm/n10_nat.t, t/vm/n20_name.t
This should ease the creation of debian packages for @ecrespo
issue #717
=> fix(test): run tests with non-root user

rvd_front.pl, templates/ng-templates/new_user.html.ep
Thanks to @jlopezramos for reporting
issue #715
=> fix(frontend): check admin rights

docs/docs/recomendations.rst
Description to use the qemu agent on KVM machines.
This functionality needs a backend functionality that automates the time sync when resume.
https://github.com/UPC/ravada/issues/466
=> [466]Full documentation for qemu guest agent

lib/Ravada/VM/KVM.pm, t/kvm/a10_pools.t
=> fix(backend): use default defined storage

docs/docs/INSTALL_Script.rst
Deleted '_' that brakes the downloadable link.
=> Fixed broken link

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/Void.pm, lib/Ravada/Front/Domain.pm, rvd_front.pl, templates/main/vm_options.html.ep
Added the possibility to enable the property 'volatile_clones' from the front-end
https://github.com/UPC/ravada/issues/678
=> 678 volatile clones

lib/Ravada/VM/KVM.pm, t/kvm/a10_pools.t
=> test(backend): test base prepared in default storage

lib/Ravada/Domain/KVM.pm, t/kvm/a10_pools.t
always prepare base on default storage pool
=> 720 storage

lib/Ravada/Domain/KVM.pm
delete the xml if domain is base
close #672
=> fix(backend): delete the xml from DB when the VM is removed

t/lib/Test/Ravada.pm, t/user/20_grants.t, t/user/30_grant_remove.t
=> test(grants): list virtual machines

lib/Ravada/Auth/SQL.pm, lib/Ravada/Domain.pm, lib/Ravada/Front.pm, lib/Ravada/Request.pm, rvd_front.pl, t/lib/Test/Ravada.pm, t/user/20_grants.t, t/user/30_grant_remove.t, t/user/40_grant_shutdown.t, templates/main/admin_machines.html.ep
=> #710 shutdown all

lib/Ravada/Auth/SQL.pm, t/user/50_admin.t
=> fix(users): revoke only enabled grants

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/VM.pm, lib/Ravada/VM/KVM.pm, lib/Ravada/VM/Void.pm, rvd_front.pl, sql/mysql/domains_kvm.sql, sql/mysql/domains_void.sql, sql/sqlite/domains_kvm.sql, sql/sqlite/domains_void.sql, t/kvm/20_domain_kvm.t, t/vm/v10_volatile.t, t/vm/v20_volatile_clones.t
Clean volatile clones on shutdown
=> #629 clean

lib/Ravada.pm, lib/Ravada/Request.pm, rvd_front.pl, t/vm/10_domain.t, templates/main/vm_options.html.ep
=> 688 owner machine

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/VM/KVM.pm
Automate Sync Time on resume KVM machine.
https://github.com/UPC/ravada/issues/466
=> 466 auto sync clock

public/js/admin.js, rvd_front.pl, templates/main/admin_machines.html.ep, templates/main/settings_machine_tabs_body.html.ep, templates/main/settings_machine_tabs_head.html.ep
Checks first if access to port 19999 is ok, then reloads
and enables monitoring
issue #756
=> fix(monitoring): enable monitoring only if accessible

lib/Ravada.pm, lib/Ravada/I18N/en.po, lib/Ravada/Request.pm, rvd_front.pl, t/vm/10_domain.t, templates/main/vm_options.html.ep
=> Revert "#688 owner machine"

lib/Ravada/Domain.pm
=> fix(frontend): show if domain has clones

CHANGELOG.md, etc/xml/bionic-amd64.xml, etc/xml/bionic-i386.xml, etc/xml/bionic32-volume.xml, etc/xml/bionic64-volume.xml, lib/Ravada.pm
=> #709 bionic

lib/Ravada.pm, lib/Ravada/Auth/SQL.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Front.pm, lib/Ravada/Request.pm, lib/Ravada/VM.pm, lib/Ravada/VM/KVM.pm, lib/Ravada/VM/Void.pm, rvd_front.pl, sql/mysql/domains_kvm.sql, sql/mysql/domains_void.sql, sql/sqlite/domains_kvm.sql, sql/sqlite/domains_void.sql, t/35_request_start.t, t/user/20_grants.t, t/user/30_grant_remove.t, t/user/40_grant_shutdown.t, t/user/50_admin.t, t/vm/20_base.t, t/vm/t10_timeout.t, t/vm/v10_volatile.t, t/vm/v20_volatile_clones.t
This is for branch: 710_shutdown_all
=> feat(frontend): shutdown all

public/js/admin.js, rvd_front.pl, templates/main/admin_machines.html.ep, templates/main/settings_machine_tabs_body.html.ep, templates/main/settings_machine_tabs_head.html.ep
=> fix(monitoring): check port accessible

lib/Ravada.pm, lib/Ravada/I18N/en.po, lib/Ravada/Request.pm, rvd_front.pl, t/vm/10_domain.t, templates/main/vm_options.html.ep
=> feat: owner machine

lib/Ravada/I18N/en.po, public/js/ravada.js, rvd_front.pl, templates/main/list_bases_ng.html.ep, templates/main/list_bases_ng_head.html.ep, templates/main/run_request.html.ep
=> feat(frontend): dynamic list bases

lib/Ravada/I18N/en.po, public/js/ravada.js, rvd_front.pl, templates/main/list_bases_ng.html.ep, templates/main/list_bases_ng_head.html.ep, templates/main/run_request.html.ep
=> feat(i8n): list bases

lib/Ravada.pm, lib/Ravada/Auth/SQL.pm, lib/Ravada/Domain.pm, sql/mysql/grant_types_alias.sql, sql/sqlite/grant_types_alias.sql, t/user/20_grants.t
=> feat(grants): grants aliases

rvd_front.pl
It must be owned by the user and cloned from the base
issue #740
=> fix(frontend): create another if not suitable clone

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/VM.pm, lib/Ravada/VM/KVM.pm, lib/Ravada/VM/Void.pm, t/vm/m10_freemem.t, templates/main/run_request.html.ep
=> feat(backend): check free memory

lib/Ravada/Domain.pm, t/vm/20_base.t, t/vm/v10_volatile.t
Branch  **fix/765_remove_clones**
=> fix(frontend): remove clones

lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, public/js/ravada.js, t/request/60_start.t, t/vm/20_base.t
=> Fix:(backend): iptables down

t/vm/35_remove2.t
=> [#793]Tests remove domain kvm added

lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/VM.pm, lib/Ravada/VM/KVM.pm, public/js/ravada.js, t/vm/v10_volatile.t
Volatile clones are gone on shutdown in KVM and we should deal with it when checking if active
=> volatile test #629 

index.html
Signed-off-by: Gianfranco Manganiello <gmanganiello@teclib.com>
In this PR:
- Update the years of Perl development
The year was outdated by one, this can be checked in the official documentation of Perl.
Ref: https://www.perl.org/
=> Years of Perl development

.gitignore, lib/Ravada.pm, lib/Ravada/Front/Domain/KVM.pm, lib/Ravada/Request.pm, rvd_front.pl, t/vm/m20_memory.t, templates/main/vm_options.html.ep
=> 692 change vm memory

lib/Ravada/I18N/en.po, templates/bootstrap/user_settings.html.ep
Issue [#701]
Add portuguese language option
=> feat(i18n):add portuguese

bin/rvd_back.pl, lib/Ravada.pm, lib/Ravada/Front.pm, lib/Ravada/Request.pm, t/vm/20_base.t
Speed up the backend making the cleanup process
regular requests
issue #828
=> fix(backend): clenup process as requests

rvd_front.pl
=> 03_beta6 permisions fix

lib/Ravada/I18N/ca.po, lib/Ravada/I18N/es.po, lib/Ravada/I18N/fr.po
Update from transifex
French review pending
issue [#827]
=> feat(i18n):update fr, ca & es

lib/Ravada/I18N/en.po, templates/bootstrap/authors.html.ep, templates/main/about.html.ep, templates/main/run_request.html.ep, templates/main/vm_copy.html.ep, templates/main/vm_description.html.ep, templates/main/vm_drivers.html.ep, templates/main/vm_hardware.html.ep, templates/main/vm_remove.html.ep, templates/main/vm_rename.html.ep, templates/main/vm_screenshot.html.ep
All texts are localized in the templates
Some texts aren't localized.
Improve product quality
=> 424 check i18n

package.json, templates/bootstrap/scripts.html.ep
Issue [#860]
Upgrade a new version
=> fix(frontend):upgrade jquery version

lib/Ravada/I18N/ca.po, lib/Ravada/I18N/es.po
Update from transifex
Issue #862
=> feat(i18n):update ca & es

lib/Ravada/I18N/id.po
- Removed repeated entries in id.po
- Upload manually to Transifex too.
Issue #874 & #398
=> fix(i18n): id.po remove repeated entries

lib/Ravada/Auth/LDAP.pm
=> [#645] Check login to allowed users in posix_group

lib/Ravada/I18N/zh_CN.po, lib/Ravada/I18N/zh_TW.po
=> wip(i18n): Add Chinese po files for China & Taiwan

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Domain/Void.pm, lib/Ravada/Front/Domain/KVM.pm, lib/Ravada/Request.pm, lib/Ravada/VM.pm, rvd_front.pl, t/front/20_create_domain.t, t/lib/Test/Ravada.pm, templates/main/run_request.html.ep
show the virtual machine internal IP address on startup
=> Feature #465 internal ip

lib/Ravada/I18N/en.po, templates/main/new_node.html.ep
- Add new entries in en.po file
- Fix buttons
Issue [#881]
=> fix(frontend): form new node

docs/docs/INSTALL.rst
=> Updated INSTALL.rst

t/65_user_ldap.t, t/README_ldap.md, t/front/60_ldap.t, t/lib/Test/Ravada.pm
Tests also when configured ldap posix group
=> Test #887 ldap

lib/Ravada/Domain.pm, lib/Ravada/Front.pm, lib/Ravada/VM.pm, t/65_user_ldap.t, t/README_ldap.md, t/front/60_ldap.t, t/lib/Test/Ravada.pm, t/vm/v20_volatile_clones.t
Faster clone+start for release 0.3.0
=> Feature #894 master

lib/Ravada.pm, lib/Ravada/VM.pm, t/65_user_ldap.t, t/vm/v20_volatile_clones.t
=> Feature #894 clone start

lib/Ravada/I18N/fr.po
translation to correct some spelling mistakes such as "utilizateurs" and change some French words like "hiberner" to "mise en veille" which are preferred.
Addressing issue #398
=> Improve French translation

rvd_front.pl
=> Fix #848 raptor on master

lib/Ravada.pm
Option to start more than one machine added
=> add start_many machines option

lib/Ravada.pm, lib/Ravada/Auth.pm, lib/Ravada/Auth/LDAP.pm, lib/Ravada/Auth/SQL.pm, lib/Ravada/Auth/User.pm, lib/Ravada/Domain.pm, lib/Ravada/Front.pm, lib/Ravada/I18N/id.po, sql/mysql/access_ldap_attribute.sql, sql/sqlite/access_ldap_attribute.sql, t/65_user_ldap.t, t/front/70_ldap_access.t, t/lib/Test/Ravada.pm
Tests and authorization based LDAP attributes as requested by @petit76
=> Feature #904 ldap attributes

lib/Ravada/Front.pm, lib/Ravada/VM.pm, public/js/admin.js, rvd_front.pl, templates/main/admin_nodes.html.ep
New variable in the template scope for disable (or not) the remove node button
check if the node have active machines, is localhost or have bases
if true, add a var to the list
the value of this var is shown in the template to disabled the button
The directive ng-disable does not work correctly in that context.
https://github.com/UPC/ravada/issues/870
closes #870
=> feature: new button remove node

lib/Ravada/Domain.pm
reload max limit and not necessary reload rvd_back
=> Load max limit changes without rvd_back restart

README.md
=> Changes made in documentation

lib/Ravada/Auth/SQL.pm, lib/Ravada/Auth/User.pm, lib/Ravada/Domain.pm, sql/mysql/access_ldap_attribute.sql, sql/sqlite/access_ldap_attribute.sql, t/README_ldap.md, t/front/70_ldap_access.t, t/lib/Test/Ravada.pm
Denies access by LDAP attribute
=> Feature #922 deny access

lib/Ravada/Domain/KVM.pm, t/kvm/80_hibernated.t
If it fails starting a hibernated KVM domain it removes the saved state and tries to start again
=> Fix #587 crashed

lib/Ravada/Auth/LDAP.pm
Connect to LDAP with SSL to non-standard ports
Suggested by @dani-sanchez-dorado
=> Feature #823 ldap secure

rvd_front.pl
Changing page when create new node
=> improve new node #919

sql/mysql/bases.sql, sql/sqlite/access_ldap_attribute.sql, sql/sqlite/bases.sql, t/99_stress.t, t/etc/sql.conf, t/front/70_ldap_access.t, t/kvm/80_hibernated.t, t/lib/Test/Ravada.pm, t/lxc/20_domain_lxc.t, t/request/60_start.t, t/user/30_grant_remove.t, t/user/40_grant_shutdown.t, t/vm/35_remove2.t, t/vm/m10_freemem.t, t/vm/m20_memory.t
=> Test #933 ldap

templates/main/admin_machines.html.ep
show autostart option if machine has not clones and it is not a base
=> fix option to active autostart machines

docs/docs/INSTALL_Fedora.rst, docs/docs/change_windows_driver_to_virtio.rst, docs/docs/custom_footer.rst, docs/docs/local_resources.rst, docs/docs/monitoring.rst, docs/docs/new_documentation.rst, docs/docs/resize_hard_drive.rst, docs/docs/resize_hard_drive_linux_machine.rst, docs/docs/troubleshooting.rst
=> fix(docs): fix warnings

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Front.pm, lib/Ravada/Request.pm, lib/Ravada/VM.pm, lib/Ravada/VM/KVM.pm, t/kvm/n10_nodes.t, t/kvm/n20_nodes_hibernate.t, t/lib/Test/Ravada.pm, t/nodes/10_basic.t, t/nodes/20_dead_node.t, templates/main/admin_nodes.html.ep
Better management of dead nodes
=> Feature #882 dead node

templates/bootstrap/navigation.html.ep, templates/bootstrap/user_settings.html.ep, templates/main/list_bases_ng.html.ep, templates/main/show_requests.html.ep, templates/main/vm_remove.html.ep, templates/ng-templates/new_machine_other.html.ep
=> 927 fix html

bin/rvd_back.pl, etc/repository/iso/ca/linkat_1804.yml, etc/repository/iso/ca/linkat_lleugera_amd64_1804.yml, etc/repository/iso/ca/linkat_lleugera_i386_1804.yml, lib/Ravada.pm, lib/Ravada/Front.pm, lib/Ravada/Repository/ISO.pm, lib/Ravada/Request.pm, lib/Ravada/VM/KVM.pm, rvd_front.pl, t/00_libs.t, t/lib/Test/Ravada.pm, t/repository/10_iso.t, t/request/20_download_local.t, templates/ng-templates/new_machine_template.html.ep
=> Feature #959 linkat

lib/Ravada/Domain.pm, t/lib/Test/Ravada.pm, t/nodes/40_storage.t
Check storage pools defined for local and remote nodes, closes issue #969
=> Feature #969 pools

debian/control, lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Domain/Void.pm, lib/Ravada/Front/Domain.pm, lib/Ravada/VM.pm, lib/Ravada/VM/KVM.pm, lib/Ravada/VM/Void.pm, rvd_front.pl, t/kvm/t10_tls.t, t/lib/Test/Ravada.pm, templates/main/run_request.html.ep
Allows secure connections with SPICE, closes #249
=> Feature #249 tls

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Domain/Void.pm, lib/Ravada/Front/Domain.pm, lib/Ravada/Front/Domain/KVM.pm, lib/Ravada/Front/Domain/Void.pm, lib/Ravada/Request.pm, lib/Ravada/Utils.pm, lib/Ravada/VM.pm, lib/Ravada/VM/KVM.pm, lib/Ravada/VM/Void.pm, public/js/ravada.js, rvd_front.pl, sql/data/insert_domain_drivers_options.sql, sql/data/insert_domain_drivers_types.sql, sql/mysql/volumes.sql, sql/sqlite/volumes.sql, t/15_utils.t, t/front/10_load.t, t/kvm/22_domain_kvm_base.t, t/kvm/65_dom_settings_req.t, t/lib/Test/Ravada.pm, t/request/30_hardware.t, t/request/40_base.t, t/vm/40_volumes.t, t/vm/60_dom_settings.t, t/vm/c10_copy.t, t/vm/d20_disks.t, templates/main/vm_hardware.html.ep
=> Feature #198 disk

lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, rvd_front.pl, t/vm/m20_memory.t, templates/main/vm_options.html.ep
=> Feature #966 ram

lib/Ravada/Request.pm, rvd_front.pl, t/repository/10_iso.t
=> fix(frontend): pass user name in post login

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Domain/Void.pm, lib/Ravada/Front/Domain.pm, lib/Ravada/VM/Void.pm, public/js/ravada.js, rvd_front.pl, sql/mysql/volumes.sql, sql/sqlite/volumes.sql, t/kvm/22_domain_kvm_base.t, t/kvm/a10_pools.t, t/kvm/a20_xml.t, t/request/30_hardware.t, t/request/40_base.t, t/vm/30_remove.t, t/vm/40_volumes.t, t/vm/45_vol_swap.t, t/vm/c10_copy.t, t/vm/d20_disks.t, templates/main/manage_machine_new_disk.html.ep, templates/main/vm_hardware.html.ep
=> Feature #973 cd

lib/Ravada/VM/KVM.pm
=> fix(backend): clean machine type before starting on remote

templates/main/admin_monitoring.html.ep, templates/main/admin_nodes.html.ep, templates/main/admin_users.html.ep, templates/main/new_node.html.ep
Issue #960
Hardcoded footer %= include 'bootstrap/footer' in templates
proposed by @Klius
=> fix(footer):replace hardcoded footer

lib/Ravada/I18N/ca.po, lib/Ravada/I18N/en.po, lib/Ravada/I18N/es.po
added msgid at en.po and msgid/msgstr at es.po for test
fixes #989
=> fix #989: No I18N in message at login page

docs/devel-docs/create_grants.rst, docs/docs/gpu.rst
documentation about how grants system works and references about how to do a test for it.
docs #996
=> docs: How to create a new grant

lib/Ravada/Domain.pm
Do not check is active machine so many times and do not wait for down if no swap volumes.
=> Refactor #1012 info

lib/Ravada/Domain.pm, lib/Ravada/VM.pm, t/kvm/n10_nodes.t, t/user/30_grant_remove.t
=> Feature #1104 storage

lib/Ravada/VM/KVM.pm, t/kvm/s20_sysinfo.t, t/user/40_grant_shutdown.t
Add smbios string hostname to the virtual machine
=> Feature #1010 smbios

lib/Ravada/Front.pm, rvd_front.pl
- On list_base_anonymous add bind similar to list_machine_user so list_base_ng.html.ep parse don't fail
- Add check $USER is not defined on '/img/screenshots/:file'
fix #1016
=> fix: screenshot image anonymous

lib/Ravada/Domain.pm, t/lib/Test/Ravada.pm, t/nodes/10_basic.t, t/nodes/50_three_nodes.t
Fixes removes when there are instances of virtual machine in remote nodes
=> Fix #1026 remove

lib/Ravada/Auth/SQL.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/Void.pm, lib/Ravada/Utils.pm, lib/Ravada/VM/KVM.pm, t/lib/Test/Ravada.pm, t/nodes/10_basic.t, t/nodes/50_three_nodes.t, t/nodes/60_hardware.t, templates/main/settings_machine_tabs_body.html.ep, templates/main/vm_hardware.html.ep
Cleanup node instances when changing hardware
=> Fix #1025 hardware

etc/xml/alpine-i386.xml, lib/Ravada.pm
=> fix(ISO): remove Alpine from ISO list

Makefile.PL, debian/control, lib/Ravada/Request.pm
=> refactor(backend): no need for Date::Calc anymore

lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/VM.pm, lib/Ravada/VM/KVM.pm, lib/Ravada/VM/Void.pm, t/kvm/a10_pools.t, t/vm/40_volumes.t
=> Refactor #10 disk

lib/Ravada.pm, lib/Ravada/Request.pm
=> refactor(requests): run request after_request

lib/Ravada/I18N/ca.po, lib/Ravada/I18N/es.po
- Update en.po
- Translate them into spanish and catalan
Issue #1039
=> fix(i18n): Update translations from Transifex

lib/Ravada/I18N/en.po, templates/main/start.html.ep
- Add to en.po files
Issue #1028
=> fix(i18): hardcoded

lib/Ravada/I18N/en.po, lib/Ravada/I18N/fr.po, lib/Ravada/I18N/it.po, lib/Ravada/I18N/ja.po, templates/bootstrap/user_settings.html.ep
Issue #1057
Update Japanese and French, and add a new Italian translation.
=> feat(i18n): Uptade translations & italian language

lib/Ravada/I18N/en.po, lib/Ravada/I18N/vi.po, templates/bootstrap/user_settings.html.ep
=> feat(i18n): Add Vietnamese option

t/lib/Test/Ravada.pm, t/vm/60_new_args.t
fixed test so disk size values are passed
issue #1062
=> refactor(test): default volumes small

lib/Ravada.pm, t/02_config.t, t/README_nodes.md
=> Feature #763 config

lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Domain/Void.pm, t/front/20_create_domain.t, templates/main/run_request.html.ep, templates/main/vm_options.html.ep
Fetch virtual machine IP with agent in KVM
=> Feature #465 ip agent

t/README_nodes.md, t/lib/Test/Ravada.pm, t/nodes/30_disable_node.t, t/nodes/50_three_nodes.t
=> test(nodes): testing remote nodes

lib/Ravada.pm, lib/Ravada/Request.pm, t/front/20_create_domain.t
=> Refactor #1064 requests

lib/Ravada.pm
=> feature(backend): remove unnecessary down req

lib/Ravada/Domain/KVM.pm, lib/Ravada/Domain/Void.pm, lib/Ravada/VM/Void.pm, t/vm/35_remove2.t
=> Fix #1076 remove

lib/Ravada/Domain.pm, t/nodes/10_basic.t
=> Fix #1080 vm

templates/main/new_node.html.ep, templates/ng-templates/new_machine_template.html.ep
- Check "fade in" in all alerts
Issue #1086
Fix issue
=> fix(messages): Show error messages

public/js/ravada.js, rvd_front.pl, templates/main/vm_copy.html.ep
Also improved get RAM size from base
issue #1091
=> feature(frontend): multiple copies

lib/Ravada/Domain.pm, t/vm/92_ports.t
get port exposed for x2go and others
=> Feature #265 ports 2

lib/Ravada.pm, sql/mysql/grant_types.sql, sql/mysql/users.sql, sql/mysql/volumes.sql, sql/sqlite/grant_types.sql, t/lib/Test/Ravada.pm, t/vm/92_ports.t
Fixed mariadb issues with large indexes. Hopefully will improve Debian package
=> Fix #1104 mariadb

lib/Ravada.pm, sql/data/insert_iso_images.sql
=> feature(iso): added buster

rvd_front.pl, templates/main/start.html.ep
=> feature(frontend): disable timeout check in login form

lib/Ravada/VM/KVM.pm
=> feature(backend):Set three first MAC octets as static

lib/Ravada/I18N/en.po, templates/main/machine_access.html.ep, templates/main/machine_access_list.html.ep, templates/main/machine_access_new.html.ep, templates/main/settings_machine_tabs_body.html.ep, templates/main/settings_machine_tabs_head.html.ep
Fix the missing access option in settings machine 
Fix the issue
Upgrade to bootstrap 4
=> 1098 access

lib/Ravada/Auth/LDAP.pm, t/65_user_ldap.t, t/front/60_ldap.t
enforce check of login exact match
fixes issue #1100
=> fix(frontend): login with spaces now fails

CHANGELOG.md, lib/Ravada.pm, lib/Ravada/Front.pm, lib/Ravada/Request.pm, lib/Ravada/VM/KVM.pm, t/request/15_download.t, templates/bootstrap/footer.html.ep
regexp search fixed and outdates removed
=> Fix #1125 iso

lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Domain/Void.pm, lib/Ravada/Front/Domain.pm, lib/Ravada/Front/Domain/KVM.pm, lib/Ravada/Front/Domain/Void.pm, lib/Ravada/VM.pm, lib/Ravada/VM/KVM.pm, lib/Ravada/VM/Void.pm, lib/Ravada/Volume.pm, lib/Ravada/Volume/Class.pm, lib/Ravada/Volume/ISO.pm, lib/Ravada/Volume/QCOW2.pm, lib/Ravada/Volume/RAW.pm, lib/Ravada/Volume/Void.pm, public/js/ravada.js, t/20_volumes.t, t/kvm/20_domain_kvm.t, t/kvm/65_dom_settings_req.t, t/kvm/r10_raw.t, t/lib/Test/Ravada.pm, t/request/30_hardware.t, t/vm/20_base.t, t/vm/40_volumes.t, t/vm/55_rename.t, t/vm/c10_copy.t, t/vm/d20_disks.t, templates/main/vm_hardware.html.ep
=> refactor volume management

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Request.pm, lib/Ravada/VM.pm, public/js/ravada.js, rvd_front.pl, t/55_freemem.t, t/lib/Test/Ravada.pm, t/vm/p10_pools.t, templates/main/admin_machines.html.ep, templates/main/settings_machine.html.ep, templates/main/settings_machine_tabs_body.html.ep, templates/main/vm_ports.html.ep
Fixed create clones when pooling
=> Fix #1131 pool

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Request.pm, lib/Ravada/VM.pm, lib/Ravada/VM/KVM.pm, lib/Ravada/VM/Void.pm, rvd_front.pl, t/kvm/40_import.t, t/lib/Test/Ravada.pm, t/user/20_grants.t, t/vm/92_ports.t, templates/main/vm_ports.html.ep
Expose after hibernate
fixes #1134
=> Fix ports expose

lib/Ravada/Domain.pm, lib/Ravada/VM/KVM.pm, t/lib/Test/Ravada.pm, t/request/30_hardware.t, t/vm/20_base.t, t/vm/40_volumes.t
Recovers from failed prepare base
=> Fix prepare base

templates/main/list_bases_ng.html.ep, templates/main/settings_machine_tabs_body.html.ep
=> fixed with ng-cloak

lib/Ravada/Domain/KVM.pm, t/kvm/s20_sysinfo.t
Set hostname on rename
fixes #1146
=> smbios hostname

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/VM.pm, t/kvm/n10_nodes.t, t/lib/Test/Ravada.pm, t/nodes/10_basic.t, t/vm/92_ports.t, templates/main/run_request.html.ep
=> fix(networking): properly deny restricted ports

templates/ng-templates/new_user.html.ep
Only show errors when the field loses focus
Added a "Show password" button
"Cancel" button now redirects to the users page (before it redirected to the VMs page)
fixes #1140
=> fix(frontend): Improve users management in admin

docs/docs/windows_clients.rst
=> Revert "Update windows_clients.rst"

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/VM.pm, t/kvm/n10_nodes.t, t/lib/Test/Ravada.pm, t/nodes/10_basic.t, t/vm/92_ports.t, templates/main/run_request.html.ep
Deny access to exposed ports properly
=> Fix ports exposed

.gitignore, t/etc/ds389.conf, t/etc/ravada_ldap.conf, t/front/60_ldap.t, t/lib/Test/Ravada.pm
Make sure it tests ok and runs
=> Refactor for ubuntu eoan

templates/ng-templates/new_machine_template.html.ep
Disk, Swap and RAM numeric entry
Enable SWAP volumes by default on new machine
Minimum disk size entry set by the selected ISO
fixes #1150 & #1154
=> fix(frontend): Improve new machine page

.gitignore, bin/rvd_back.pl, lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/VM.pm, sql/mysql/storage_nodes.sql, sql/sqlite/storage_nodes.sql, t/etc/ds389.conf, t/etc/ravada_ldap.conf, t/front/60_ldap.t, t/kvm/n10_nodes.t, t/lib/Test/Ravada.pm
Fix slow management of guests in other nodes
=> Refactor nodes

lib/Ravada.pm, lib/Ravada/Auth/User.pm, lib/Ravada/Domain.pm, lib/Ravada/Front.pm, lib/Ravada/Request.pm, lib/Ravada/WebSocket.pm, public/js/admin.js, public/js/ravada.js, rvd_front.pl, templates/bootstrap/messages.html.ep, templates/main/admin_machines.html.ep, templates/main/admin_messages.html.ep, templates/main/admin_monitoring.html.ep, templates/main/settings_machine.html.ep, templates/main/settings_machine_tabs_body.html.ep, templates/main/vm_hardware.html.ep, templates/main/vm_pool.html.ep, templates/main/vm_rename.html.ep
Websockets to replace some pulls
* list alerts
* list machines
* list requests
* machine info
closes #1187
=> Refactor websockets

lib/Ravada.pm, sql/mysql/requests.sql
Creates requests with new on update timestamp. Also upgrades if already created.
=> Fix #1204 timestamp

lib/Ravada.pm, lib/Ravada/Front.pm, lib/Ravada/Request.pm, lib/Ravada/WebSocket.pm, public/js/admin.js, public/js/ravada.js, rvd_front.pl, templates/bootstrap/messages.html.ep, templates/bootstrap/requests.html.ep, templates/main/admin_machines.html.ep, templates/main/check_ws.html.ep, templates/main/list_bases_ng.html.ep, templates/main/list_bases_ng_head.html.ep, templates/main/manage_machine_new_disk.html.ep, templates/main/settings_machine.html.ep, templates/main/vm_copy.html.ep, templates/main/vm_hardware.html.ep, templates/main/vm_rename.html.ep
Port more *pull* code to *web service*
=> Refactor frontend web service

lib/Ravada.pm, lib/Ravada/Auth/LDAP.pm, t/65_user_ldap.t, t/etc/ravada_ldap.conf
=> Refactor #1208 ldap

t/nodes/60_hardware.t
Check drivers are kept on migration
=> Fix #1135 drivers 

lib/Ravada/Front.pm, lib/Ravada/WebSocket.pm, public/js/admin.js, public/js/ravada.js, rvd_front.pl
Properly ping backend without pestering the requests table
=> Refactor #1196 ping

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/VM/KVM.pm, public/js/admin.js, public/js/ravada.js, rvd_front.pl, sql/mysql/users.sql, sql/sqlite/users.sql, t/vm/v10_volatile.t
=> Fix #1023 anonymous users don't get deleted

public/js/ravada.js, templates/main/list_bases_ng.html.ep
slightly improved on the flickering problem
=> Refactor #1228 action

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Domain/Void.pm, lib/Ravada/Request.pm, lib/Ravada/VM.pm, lib/Ravada/VM/KVM.pm, lib/Ravada/Volume/Class.pm, lib/Ravada/Volume/ISO.pm, lib/Ravada/Volume/QCOW2.pm, lib/Ravada/Volume/Void.pm, public/js/ravada.js, t/lib/Test/Ravada.pm, t/vm/10_domain.t, t/vm/20_base.t, t/vm/47_vol_data.t, t/vm/r20_rebase.t, t/vm/s10_spinoff.t, templates/main/vm_base.html.ep, templates/main/vm_prepare_base.html.ep, templates/main/vm_rebase.html.ep, templates/main/vm_remove_base.html.ep, templates/main/vm_spinoff.html.ep
Improved spinoff, remove base and improved base actions in frontend.
=> Refactor spinoff

CONTRIBUTING.md
=> I explain how clean up a fork and restart it from upstream

lib/Ravada/I18N/ar.po, templates/bootstrap/user_settings.html.ep
=> Arabic translate

dockerfy/docker-compose.yml
Downgrade compose version 3.5 to 2.2
https://docs.docker.com/compose/compose-file/
Issue #1248
=> feat(compose): more compatibility with old docker

lib/Ravada.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/VM/KVM.pm, t/lib/Test/Ravada.pm, t/request/20_download_local.t
Some operations return 
`libvirt error code: 1, message: internal error: pool 'default' has asynchronous jobs running`
Wait for this to finish so we can run the task
=> Wait for busy Storage  Pools

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Domain/Void.pm, lib/Ravada/VM.pm, t/kvm/n10_nodes.t, t/kvm/p10_password.t, t/lib/Test/Ravada.pm, t/nodes/10_basic.t
=> fix(backend): improved listen ip for display

lib/Ravada/Domain.pm, lib/Ravada/VM.pm
=> Fastest start with many nodes

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Request.pm, lib/Ravada/VM.pm, lib/Ravada/VM/KVM.pm, lib/Ravada/Volume/QCOW2.pm, lib/Ravada/Volume/Void.pm, rvd_front.pl, t/kvm/n10_nodes.t, t/lib/Test/Ravada.pm, t/nodes/10_basic.t, t/nodes/60_hardware.t, t/vm/r20_rebase.t, templates/main/vm_base.html.ep
=> Fix base file on remote node

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/VM.pm, t/kvm/n10_nodes.t, t/kvm/n20_nodes_hibernate.t, t/nodes/10_basic.t
Try to reuse same remote node for virtual machines.
=> Refactor same node

lib/Ravada/Auth/LDAP.pm, public/js/ravada.js, rvd_front.pl, t/front/70_ldap_access.t
Restored code previously deleted. I wanted to consolidate on access restrictions but we have to settle this down sometime.
=> Fix ldap access restrictions

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Domain/Void.pm, lib/Ravada/Front/Domain.pm, lib/Ravada/Request.pm
=> refactor(backend): retry set date

lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Request.pm, t/kvm/n10_nodes.t, t/lib/Test/Ravada.pm, t/request/60_start.t, t/vm/10_domain.t, t/vm/20_base.t, t/vm/90_fw.t, t/vm/92_ports.t, t/vm/p10_pools.t, t/vm/t10_timeout.t
The new set time request made some test fail because
it wasn't expected before.
issue #1279
=> refactor(test): fixed some tests when set time

lib/Ravada/WebSocket.pm, public/js/admin.js, templates/main/admin_machines.html.ep
- Removed order by other fields
- Also tweaked ping backed so it is more accurate
issue #1276
=> refactor(frontend): turn list machines into a hash

lib/Ravada.pm, lib/Ravada/Request.pm, lib/Ravada/VM.pm, t/vm/10_domain.t, templates/main/vm_clones.html.ep
Issue #1287
Allow shutdown all the clones from settings.
=> feat(settings): Shutdown all clones from settings

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/VM.pm, t/nodes/10_basic.t, t/vm/10_domain.t
Disconnected machines are shut down
=> Feature shutdown disconnected

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/VM/Void.pm, lib/Ravada/Volume.pm, lib/Ravada/Volume/Class.pm, t/kvm/n20_nodes_hibernate.t, t/nodes/10_basic.t, t/nodes/60_hardware.t, t/vm/10_domain.t, t/vm/30_remove.t, t/vm/35_remove2.t
When a volume is created, check it is not being used by another virtual machine.
closes #1285
=> Fix renamed vol

lib/Ravada.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/VM/KVM.pm, t/kvm/72_add_nic.t, t/mojo/10_login.t
Creates network hardware with unique MAC.
=> Fix duplicated mac

lib/Ravada.pm, lib/Ravada/Front.pm, lib/Ravada/WebSocket.pm, public/js/admin.js, public/js/ravada.js, script/rvd_front, templates/main/admin_machines.html.ep, templates/main/vm_options.html.ep
Faster loading of list machines when many clones
=> Refactor admin machines

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/Void.pm, lib/Ravada/VM.pm, lib/Ravada/VM/KVM.pm, lib/Ravada/VM/Void.pm, t/55_freemem.t, t/lib/Test/Ravada.pm, t/mojo/20_ws.t, t/nodes/10_basic.t
=> Fix node out of memory

etc/fallback.conf, templates/bootstrap/scripts.html.ep
PR #1175
Upgrade angularjs to 1.7.8
=> fix(deps): angularjs update

etc/xml/alpine-amd64.xml, etc/xml/alpine-i386.xml, etc/xml/bionic-amd64.xml, etc/xml/bionic-i386.xml, etc/xml/empty-i386.xml, etc/xml/mint19-i386.xml, etc/xml/windows_10.xml, etc/xml/windows_12.xml, etc/xml/windows_7.xml, etc/xml/windows_8.xml, etc/xml/windows_xp.xml, etc/xml/xenial-i386.xml, etc/xml/xenial64-amd64.xml, etc/xml/yakkety64-amd64.xml
Some xml files don't has recommended items
Issue #1302
=> fix(xml): Fix graphics recommendations

lib/Ravada/Auth/LDAP.pm, t/65_user_ldap.t
=> fix(auth): posix group set with a dn

docs/docs/spice.reg
=> fix(doc): update version spice in reg file

Makefile.PL, debian/control-debian-10, debian/control-ubuntu-18.04, debian/control-ubuntu-19.04, debian/control-ubuntu-20.04, lib/Ravada.pm, lib/Ravada/Front.pm, public/js/admin.js, public/js/ravada.js, script/rvd_front, templates/bootstrap/navigation.html.ep, templates/main/admin_settings.html.ep, templates/main/maintenance.html.ep
Set the frontend in maintenance mode. Closes issue #1310
=> Feature maintenance mode

docs/docs/INSTALL_devel.rst, docs/docs/INSTALL_mysql.rst
Moved the MySQL install instructions to a separated document.
=> doc: mysql install

lib/Ravada.pm, t/request/30_hardware.t
Refresh locked machines after change hardware
=> Fix locked in admin machines

lib/Ravada/Domain.pm, t/nodes/10_basic.t
Only remove volume for clones after change hardware
=> Fix do not remove volume

lib/Ravada.pm, lib/Ravada/VM.pm, t/nodes/10_basic.t
=> fix(nodes): balance create volatile machines

script/rvd_front
=> feature(frontend): use Mojo log in frontend

lib/Ravada.pm, lib/Ravada/Auth/SQL.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/VM.pm, lib/Ravada/VM/KVM.pm, lib/Ravada/Volume/QCOW2.pm, public/js/admin.js, script/rvd_front, t/nodes/10_basic.t
=> Fix remove volatile volumes in nodes

script/rvd_front, templates/bootstrap/user_settings.html.ep
=> refactor(frontend): language settings improved

lib/Ravada.pm, lib/Ravada/VM.pm, lib/Ravada/VM/KVM.pm, t/lxc/22_domain_limits_lxc.t, t/lxc/24_clone_spice_lxc.t, t/request/70_network.t
Moved code from KVM to generic virtual managers
=> Refactor list networks

lib/Ravada/Domain.pm, t/vm/90_fw.t
=> refactor(backend): clean iptables table

script/rvd_front, templates/bootstrap/user_settings.html.ep, templates/main/about.html.ep
Changes to solve some javascript errors in about and user_settings sections.
To solve the errors is necessary delete ng-controllers in templates sections that are undefined.  
When I deleted the ng-controller in user_settings section the password form doesn't work. Now it works ok.
#1365
=> solve some console errors in about and user settings section

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Domain/Void.pm, lib/Ravada/Volume.pm, lib/Ravada/Volume/QCOW2.pm, t/20_volumes.t, t/lib/Test/Ravada.pm, t/mojo/10_login.t, t/request/20_download_local.t, t/request/30_hardware.t, t/vm/40_volumes.t
When unbasing raw volumes check driver in XML definition
=> Fix raw volumes unbase

public/fallback/yarn-modules-folder-path, public/js/ravada.js, templates/main/settings_machine_tabs_head.html.ep, templates/main/vm_base.html.ep, templates/main/vm_prepare_base.html.ep, templates/main/vm_rebase.html.ep, templates/main/vm_remove_base.html.ep, templates/main/vm_spinoff.html.ep
=> Fix base form

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Domain/Void.pm, lib/Ravada/VM/KVM.pm, lib/Ravada/Volume.pm, lib/Ravada/Volume/Class.pm, lib/Ravada/Volume/QCOW2.pm, t/mojo/20_ws.t, t/nodes/10_basic.t, t/vm/45_vol_swap.t
Convert raw bases to qcow so they work in Ubuntu 20.04
=> Fix raw volumes upgrade

lib/Ravada.pm, lib/Ravada/Request.pm, lib/Ravada/VM/Void.pm, script/rvd_back, t/lib/Test/Ravada.pm, t/vm/s30_storage.t
Added check storage as a request and runs before auto start machines
=> feature(backend): check storage

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Request.pm, public/js/ravada.js, script/rvd_back, t/lib/Test/Ravada.pm, t/nodes/10_basic.t, templates/main/admin_machines.html.ep, templates/main/vm_options.html.ep
Allows manual migration of any virtual machine to any node
=> Feature migrate machine

script/rvd_front, t/40_auth_sql.t, t/lib/Test/Ravada.pm, t/mojo/10_login.t, t/mojo/20_ws.t
This test is related to @andinus pull rquest #1391
=> test(auth): check that login fails properly

docs/docs/cas_login.rst, docs/index.rst
=> Docs for cas login

docs/docs/cas_login.rst, docs/index.rst
Added a param to CAS config to logout from CAS Service when logout from Ravada
=> Update CAS docs to add logout reference

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/VM.pm, public/js/admin.js, t/nodes/10_basic.t
set per VM display and NAT IPs 
fixes issue #1397
=> Fix nodes nat

templates/main/vm_options.html.ep
Now change_settings has more options
Issue #1404
=> feat(grant): Add more option to grant

dockerfy/.env, dockerfy/docker-compose.yml, dockerfy/dockers/back/Dockerfile, dockerfy/dockers/front/Dockerfile
- remove old lines in docker-compose to clean file
- move variables to .env file instead in Dockerfile
- add missing "file" deb packet to install in ravada-back Dockerfile
- create simbolic link in ravada-back Dockerfile
- ...
Issue #1410
=> bug(dockers): fix some things in docker files

lib/Ravada/I18N/messages.pot
Create a messages.pot with all the strings from en.po
Issue #1414
=> feature(localization): add template file

templates/bootstrap/footer.html.ep
=> feature(frontend): Add weblate badge

lib/Ravada/Domain.pm, t/vm/92_ports.t
=> refactor(test): use a pre-created base to test

docs/docs/create_cert.sh
Thanks to @lperezpaz
Issue #1448
=> fix(typo): remove extra character

lib/Ravada.pm
=> fix(pools): auto-number even with only one clone

lib/Ravada.pm, t/request/15_download.t, t/vm/p10_pools.t
issue #1442 and issue #1443 into develop
=> Merge ISO files and pool fix

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/VM.pm, t/kvm/n10_nodes.t, t/kvm/p10_password.t, t/lib/Test/Ravada.pm, t/nodes/10_basic.t, t/nodes/20_dead_node.t, t/vm/n10_nat.t, templates/main/admin_settings.html.ep
Fix for Spice Password setting that failed after we added support for Ubuntu 20.04
=> Fix spice password

lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, t/mojo/10_login.t, t/mojo/20_ws.t, t/nodes/10_basic.t, t/nodes/60_hardware.t, t/vm/30_remove.t, t/vm/40_volumes.t
=> fix(backend): change hardware when running in node

lib/Ravada/Auth/LDAP.pm
=> fix(auth): continue with match if bind failed

templates/bootstrap/scripts.html.ep
https://github.com/twbs/bootstrap/issues/30553
Update to 3.5.1 version
Issue #1472
=> fix(frontend): jquery bug

public/js/admin.js
=> fix(frontend): restored removed settings

dockerfy/docker-compose.yml
tested with docker-compose config
Issue #1412
=> fix(dockers): read env file

lib/Ravada/Volume.pm, t/20_volumes.t
Fixes format detection for linked files
=> Fix #1478 link

templates/main/vm_ports.html.ep
Move action button to right into vm-ports tab (#1469)
=> Move action button to right into vm-ports tab (#1469)

templates/main/vm_rename.html.ep
Changes the vm is running error width
=> Changes the vm is running error width

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/Void.pm, lib/Ravada/Request.pm, lib/Ravada/WebSocket.pm, public/js/ravada.js, templates/main/run_request.html.ep
When a machine with exposed ports starts it shows if the ports are active or not. Also start screen has been refactored to ws
=> Feature: refresh ports

CONTRIBUTING.md
=> doc: Reset branch to upstream develop

lib/Ravada.pm
new clone name takes into account the already created clones
=> new clone name takes into account the already created clones

lib/Ravada.pm
=> fix(backend): Ubuntu 20.04 URL

lib/Ravada/Domain.pm, lib/Ravada/VM.pm, lib/Ravada/VM/KVM.pm, lib/Ravada/VM/Void.pm, lib/Ravada/WebSocket.pm, t/nodes/40_storage.t
Shared storage works better now and won't fail if network is down
=> fix(nodes): shared storage detection

lib/Ravada.pm, lib/Ravada/Auth/SQL.pm, public/js/admin.js, public/js/ravada.js, script/rvd_front, sql/data/insert_grant_types.sql, templates/main/admin_machines.html.ep, templates/main/list_bases_ng.html.ep, templates/main/manage_user_grants.html.ep, templates/main/vm_actions.html.ep
Confirms machine start if limit reached
* on admin machines and machine actions
=> Confirms machine start if limit reached

lib/Ravada.pm, lib/Ravada/Domain.pm, t/30_request.t, t/request/70_network.t, t/vm/92_ports.t
=> fix(backend): ports exposing conflict fish

script/rvd_front
Disable reboot buttons if domain not active
=> Disable reboot buttons if domain not active

lib/Ravada.pm
SQL comments crashed on dockerized mysql
issue #1510
=> fix(install): remove SQL comments

etc/fallback.conf, package.json, templates/bootstrap/header.html.ep, templates/bootstrap/scripts.html.ep, templates/main/vm_drivers.html.ep, templates/main/vm_graphics.html.ep
It seems a bit incompatible with bootstrap-select lib, we removed it and now select native Bootstrap4
Removed too from failback way
Issue #1515
=> fix(1515): remove bootstrap-select to fix errors

lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/VM/KVM.pm, t/kvm/71_description_clones.t, t/kvm/a10_pools.t, t/kvm/n10_nodes.t, t/lib/Test/Ravada.pm, t/nodes/10_basic.t, t/nodes/60_hardware.t, t/nodes/70_shared.t
Updates all instances when shared storage.
fixes issue #1340
=> Fix shared storage change hardware

lib/Ravada.pm, lib/Ravada/Auth/SQL.pm, public/js/ravada.js, script/rvd_front, sql/mysql/users.sql, sql/sqlite/users.sql, templates/bootstrap/change_password.html.ep, templates/bootstrap/navigation.html.ep, templates/main/manage_user.html.ep, templates/main/manage_user_password.html.ep, templates/ng-templates/change_password.html.ep
Adds form to change user passwd
=> Adds form to change user passwd

lib/Ravada/VM/KVM.pm, t/kvm/a10_pools.t, t/lib/Test/Ravada.pm
Follows symlinks when checking file
fixes issue #1524
=> Fix linked volumes

script/rvd_front, templates/main/vm_clones.html.ep
#1527: add option to start all clones sequentially
=> #1527: add option to start all clones sequentially

lib/Ravada.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Domain/Void.pm, t/vm/92_ports.t, templates/main/run_request.html.ep
=> feat(frontend): show network interfaces hw address

script/rvd_front
=> list users in admin/users by default if number of users less to 40

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Request.pm
Define a shutdown timeout for each virtual machine
=> feat: use stored shutdown_timeout

lib/Ravada/Domain.pm, t/vm/92_ports.t, t/vm/p10_pools.t, templates/main/vm_pool.html.ep
Also show all pool machines are started if volatile
=> refactor: do not re-expose in nested bases

lib/Ravada/I18N/ca.po, lib/Ravada/I18N/en.po, lib/Ravada/I18N/es.po, templates/main/admin_machines.html.ep, templates/main/admin_settings.html.ep, templates/main/manage_machine_new_disk.html.ep, templates/main/vm_options.html.ep, templates/main/vm_prepare_base.html.ep
=> I have added to vm_options.html.ep the Shutdown Timeout

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/VM.pm, templates/main/admin_settings.html.ep, templates/main/run_request.html.ep
New setting to configure minimum port to open in the host to expose virtual machine services.
close issue #1531
=> Feat: config minimum port expose

lib/Ravada/I18N/ca-valencia.po, lib/Ravada/I18N/ca.po, lib/Ravada/I18N/es.po, lib/Ravada/I18N/fr.po, lib/Ravada/I18N/gl.po
=> Changes in languages

lib/Ravada/Domain.pm
=> Correct calculation of is_volatile value

lib/Ravada/I18N/ca-valencia.po, lib/Ravada/I18N/ca.po, lib/Ravada/I18N/en.po, lib/Ravada/I18N/es.po, lib/Ravada/I18N/fr.po, lib/Ravada/I18N/gl.po, script/rvd_front, templates/main/run_request.html.ep
=> changes on languages, machines

script/rvd_front, t/lib/Test/Ravada.pm, t/mojo/10_login.t, templates/ng-templates/new_machine_template.html.ep
Changes required for mojo9 compatibility
=> Refactor mojo9

lib/Ravada/Domain.pm, lib/Ravada/Front.pm, lib/Ravada/Request.pm, lib/Ravada/VM.pm, lib/Ravada/WebSocket.pm, public/js/ravada.js, script/rvd_front, templates/main/list_bases_ng.html.ep, templates/main/vm_copy.html.ep, templates/main/vm_options.html.ep
=> More options on copy machine

public/js/admin.js, public/js/ravada.js, templates/main/admin_machines.html.ep
=> Can view machines on new tab

lib/Ravada.pm, lib/Ravada/Auth/SQL.pm, sql/data/insert_grant_types.sql, sql/mysql/grant_types.sql, sql/sqlite/grant_types.sql, t/user/20_grants.t, t/vm/20_base.t, t/vm/80_network.t
When upgrading sets properly start limit grant, also wait for grant creation on install
=> Fix upgrade limit

lib/Ravada/Auth/LDAP.pm, public/js/admin.js, script/rvd_back, script/rvd_front, t/17_templates.t, t/65_user_ldap.t, t/66_group_ldap.t, templates/bootstrap/navigation.html.ep, templates/main/admin_group.html.ep, templates/main/admin_groups.html.ep, templates/main/admin_settings.html.ep, templates/main/vm_actions.html.ep
manage LDAP groups and members
=> Refactor(auth): groups

lib/Ravada/VM.pm, t/vm/v20_volatile_clones.t
=> clone no volatile in base volatile

lib/Ravada/Auth/LDAP.pm, lib/Ravada/Auth/SQL.pm, lib/Ravada/Booking/Entry.pm, public/js/admin.js, script/rvd_front, templates/main/manage_user.html.ep, templates/main/manage_user_groups.html.ep
Manage the groups that an user is member of
=> feature(frontend): manage user groups

lib/Ravada.pm, lib/Ravada/Auth/SQL.pm, lib/Ravada/Auth/User.pm, lib/Ravada/I18N/ca.po, public/js/admin.js, script/rvd_front, t/mojo/10_login.t, t/mojo/30_grants.t, t/user/20_grants.t, templates/main/manage_user.html.ep, templates/main/manage_user_admin.html.ep, templates/main/manage_user_grants.html.ep
Grants are updated on click, in case of errors , those are shown on the alerts
=> refactor(frontend): responsive grants and show errors

script/rvd_front
=> Solved #1584: Warning use of unitialized value

lib/Ravada/Domain/KVM.pm
=> Get ip by arp

public/js/booking/booking.services.js, public/js/booking/ldapGroup.component.html, public/js/booking/ldapGroups.component.js
issue #1587
changed input of type select by input autocomplete for search and add groups
=> fix(frontend): choose groups by Typeahead input

public/js/booking/booking.services.js, public/js/booking/calendar.component.js, public/js/booking/ldapGroup.component.html, public/js/booking/ldapGroups.component.js
the bookings api was incorrectly receiving the entry id as booking id
=> fix(frontend): overlapping schedules check failed

public/js/booking/ldapGroup.component.html, public/js/booking/ldapGroups.component.js, templates/main/machine_access_group.html.ep
Use ldapGroup component for select group access machine
fixes issue #1588
=> fix(frontend) select group access machine

public/js/admin.js, script/rvd_front, templates/ng-templates/new_machine_template.html.ep
=> Create form improvements (#1639)

public/js/booking/ldapGroup.component.html
=> Shows all elements on LDAP group select when no text

lib/Ravada.pm, lib/Ravada/Auth/LDAP.pm, script/rvd_front, t/65_user_ldap.t, t/67_group_ldap_base.t, t/front/60_ldap.t, t/lib/Test/Ravada.pm, t/vm/20_base.t, templates/main/admin_group.html.ep
The LDAP base for the groups can be configured
=> Feat group base

lib/Ravada/Auth/LDAP.pm, lib/Ravada/Auth/User.pm, lib/Ravada/Request.pm, lib/Ravada/Utils.pm, script/rvd_front, t/front/60_ldap.t, t/front/70_ldap_access.t, t/lib/Test/Ravada.pm, t/mojo/10_login.t, t/request/40_base.t, t/vm/92_ports.t
Checks access of unprivileged users to private bases. Fixes security bug reported by Pep Bartroli
=> Fix private base

public/js/ravada.js
Removing USB hardware was failing.
=> fix(frontend): remove USB hardware

lib/Ravada.pm, lib/Ravada/Auth.pm, lib/Ravada/Auth/LDAP.pm, public/js/ravada.js, script/rvd_front
Some times ldap appears enabled when it is not. We fix it making sure the config item does not get set just checking for it
=> Fix ldap disabled

lib/Ravada/I18N/en.po, public/css/admin.css, public/js/admin.js, templates/bootstrap/requests.html.ep, templates/main/admin_machines.html.ep
=> feat(frontend): show active machines

lib/Ravada.pm, lib/Ravada/Front.pm, lib/Ravada/Request.pm, lib/Ravada/VM/KVM.pm, lib/Ravada/WebSocket.pm, public/css/admin.css, public/css/main.css, public/js/admin.js, script/rvd_back, script/rvd_front, t/17_templates.t, templates/main/new_machine.html.ep, templates/ng-templates/new_machine.html.ep, templates/ng-templates/new_machine_other.html.ep, templates/ng-templates/new_machine_template.html.ep
Improved new machine form and ISO downloading
=> Refactor: iso downloading

lib/Ravada.pm, lib/Ravada/Request.pm, lib/Ravada/VM/Void.pm, script/rvd_front, t/30_request.t, t/front/20_create_domain.t, t/lib/Test/Ravada.pm, t/mojo/10_login.t, t/request/40_base.t, t/vm/60_new_args.t
Updated tests to the new download requirement before create virtual machine from PR #1677
=> Test: ISO download before create machine

.github/workflows/github-action-test.yml, lib/Ravada/Request.pm, lib/Ravada/VM/KVM.pm, lib/Ravada/VM/Void.pm, t/request/25_create_from_iso.t
Make it work when the machine creation is requested before the ISO is downloaded.
=> Refactor: iso download before create machine

public/js/admin.js, templates/bootstrap/requests.html.ep, templates/main/admin_machines.html.ep
Show only actived when requested and improved usability
=> refactor(frontend): improved show active machines

templates/main/settings_machine.html.ep
Added connection badges to the machine view header
https://github.com/UPC/ravada/issues/1483
=> Added connection badges to the machine view header

script/rvd_front, templates/main/access_denied.html.ep
=> Apply app CSS to access_denied template

lib/Ravada.pm, lib/Ravada/Domain/Void.pm, lib/Ravada/VM/KVM.pm, lib/Ravada/VM/Void.pm, t/vm/d10_not_download.t, templates/ng-templates/new_machine_template.html.ep
Downloads and adds an extra ISO CD when configured. It is useful for Windows that requires the virtio drivers.
=> Feat: Extra iso

public/js/admin.js, script/rvd_front, t/lib/Test/Ravada.pm, templates/bootstrap/requests.html.ep, templates/main/admin_machines.html.ep
Lets the user filter by machine name
=> Filter in admin machines

lib/Ravada.pm, lib/Ravada/Auth/User.pm, lib/Ravada/Request.pm, lib/Ravada/WebSocket.pm, public/js/admin.js, public/js/ravada.js, script/rvd_front, t/30_request.t, t/55_freemem.t, t/lib/Test/Ravada.pm, t/mojo/10_login.t, t/request/25_create_from_iso.t, t/request/60_start.t, t/vm/40_volumes.t, t/vm/p10_pools.t, t/vm/v20_volatile_clones.t, templates/main/settings_machine.html.ep, templates/main/vm_remove.html.ep, templates/ng-templates/new_machine_template.html.ep
When create machine, adds swap and data drives after the create requested is finished. Eventually,  a request for start machine is added, if  the user chooses to.
=> Refactor add hardware

lib/Ravada.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/VM/KVM.pm, public/js/ravada.js, sql/data/insert_iso_images.sql, t/kvm/uefi.t, t/lib/Test/Ravada.pm, t/vm/d20_disks.t
Improved drivers and machine setup that crashed when adding CDrom IDE
=> Fix: uefi cdrom

lib/Ravada/Request.pm, templates/bootstrap/messages.html.ep, templates/main/settings_machine.html.ep, templates/main/vm_actions.html.ep, templates/main/vm_base.html.ep, templates/main/vm_clones.html.ep, templates/main/vm_copy.html.ep, templates/main/vm_hardware.html.ep, templates/main/vm_options.html.ep, templates/main/vm_ports.html.ep
refactor(frontend): reviewed alert messages
=> Refactor messages

lib/Ravada/Domain/KVM.pm, lib/Ravada/Request.pm, public/js/ravada.js, t/request/30_hardware.t, t/vm/d20_disks.t, templates/main/manage_machine_new_disk.html.ep
Network hardware removal searches now the correct item when an index and attribute is passed
=> Fix: remove hardware by index and attribute

lib/Ravada/Request.pm, public/js/ravada.js, templates/main/run_request.html.ep
Queue open ports requests one by one
Wait for open ports request before showing redirections
Suggested by Jorge Mata
=> Refactor: queue open ports

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Front/Domain/KVM.pm, lib/Ravada/WebSocket.pm, public/js/ravada.js, script/rvd_front, sql/data/insert_domain_drivers_options.sql, t/kvm/65_dom_settings_req.t, t/request/30_hardware.t, t/vm/d20_disks.t, templates/main/manage_machine_edit_net.html.ep, templates/main/manage_machine_edit_sound.html.ep, templates/main/manage_machine_edit_video.html.ep, templates/main/settings_machine_tabs_body.html.ep, templates/main/settings_machine_tabs_head.html.ep, templates/main/vm_hardware.html.ep
=> Feature: video and sound management

lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Domain/Void.pm, t/vm/92_ports.t
Only expose ports when there are nat interfaces
=> Fix: net bridge

lib/Ravada/WebSocket.pm
make sure second list machines is shown
=> Refactor: list machines

etc/xml/windows11-volume.xml, etc/xml/windows_11.xml, lib/Ravada.pm
Volume and Virtual machine definition thanks to @hamzab70
=> Feature: Windows 11

lib/Ravada/Front/Domain/KVM.pm, public/js/ravada.js, sql/upgrades/0.1.1/insert_iso_images.sql, t/request/30_hardware.t
When displaying hardware, some items have driver, other model, other name or _name
=> Test: check the hardware name is correct

lib/Ravada/Domain/KVM.pm, lib/Ravada/VM/KVM.pm, t/lib/Test/Ravada.pm, t/nodes/10_basic.t
Sets the machine name to the most similar one in the remote node.
=> Fix: migrate q35 machine

lib/Ravada/Request.pm, public/js/ravada.js, templates/main/run_request.html.ep
Just in case we want to reopen the ports redirection
=> refactor(frontend): button to reopen ports

lib/Ravada.pm, lib/Ravada/VM.pm, lib/Ravada/WebSocket.pm, script/rvd_back, t/vm/20_base.t
MySQL server load was too high just checking for changed. This has been simplified.
=> refactor: nicer database usage

script/rvd_back
=> feat: import virtual machine

lib/Ravada/WebSocket.pm
Errors where shown in the backend when requests got removed after starting the virtual machine.
=> refactor: close websocket when request removed

lib/Ravada.pm, t/lib/Test/Ravada.pm, t/vm/20_base.t, t/vm/92_ports.t
Some changes in release 1.4 made some test ports could fail.
=> Refactor test ports

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Front.pm, lib/Ravada/Front/Domain/KVM.pm, lib/Ravada/Request.pm, public/js/ravada.js, script/rvd_front, templates/main/manage_machine_edit_cpu.html.ep, templates/main/manage_machine_edit_features.html.ep, templates/main/vm_hardware.html.ep
Allow change settings for CPU and hypervisor features
=> Feat: cpu settings

dockerfy/dockers/back/Dockerfile, dockerfy/dockers/front/Dockerfile
Issue #1749
Add a new Perl package
Thanks to @rodpinst.
=> fix(docker): Add new Perl package

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Request.pm, lib/Ravada/VM.pm, lib/Ravada/VM/KVM.pm, lib/Ravada/VM/Void.pm, t/lib/Test/Ravada.pm, t/mojo/10_login.t, t/vm/20_base.t, t/vm/d30_discover.t
Currently used only for testing, but eventually we can add it to the frontend.
=> feat: discover virtual machines

lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Front/Domain/KVM.pm, lib/Ravada/Request.pm, t/kvm/feature_policy.t, templates/main/manage_machine_edit_cpu.html.ep
=> Feature: cpu features

lib/Ravada.pm, lib/Ravada/Front/Domain/KVM.pm, lib/Ravada/VM/KVM.pm
This fixes a problem with Bionic 18.04 release
=> refactor: remove the whole CD section on create base

lib/Ravada.pm
New template for Ubuntu 22.04 Jammy Jellyfish
=> Feat: ubuntu 22

public/js/admin.js, templates/main/admin_machines.html.ep
Improved button to prepare base and set public
=> Refactor: form base

script/rvd_front
Russian option in language select
=> feat(frontend): russian translation

etc/repository/iso/ru/astra_orel_2.yml, lib/Ravada.pm, t/repository/10_iso.t
Test locale triggered repositories and fixed Astra Linux URL
=> Fix: Astra URL

script/rvd_front, t/mojo/10_login.t, templates/error/no_ldap.html.ep, templates/main/machine_access.html.ep
Does not try to connect to LDAP if not available. Also a warning message is shown when trying to use these features.
Thanks to @AndrewV666
fixes #1767
=> refactor(frontend): Do not try LDAP if not available

lib/Ravada.pm
Updated URL for Alpine Linux and removed old 3.8
=> fix: URL for Alpine Linux

script/rvd_front, t/mojo/10_login.t
* test duplicated username
* test duplicated network
fixes #1779
=> fix(frontend): ignores case when checking duplicate username

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Front/Domain/KVM.pm, lib/Ravada/VM.pm, t/front/30_controllers.t, t/kvm/f20_filesystem.t, t/nodes/60_hardware.t, t/request/30_hardware.t, templates/main/manage_machine_edit.html.ep, templates/main/manage_machine_edit_filesystem.html.ep, templates/main/manage_machine_new_filesystem.html.ep, templates/main/vm_hardware.html.ep
Gives each clone a private filesystem subdirectory
=> Feat: virtiofs dir

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/I18N/ca.po, lib/Ravada/VM.pm, public/js/ravada.js, script/rvd_front, t/nodes/80_policy.t, templates/main/vm_base.html.ep, templates/main/vm_base_policy.html.ep
=> Feat: balance policy

lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/HostDevice.pm, t/device/00_host_device.t, t/device/10_templates.t, t/device/30_pci.t, t/mojo/30_settings.t
For q35 type virtual machines, slot must be 0, so we fix it before adding to the XML.
=> Fix slot conflict for host devices

script/rvd_front, t/mojo/30_grants.t
turn true to 1 only in booleans also test all grants
=> fix(frontend): start limit always set 1

script/rvd_back
Improvements in CLI for shutdown or hibernate clients as suggested by Jorge Mata at UPC.
=> Fix cli manage domains

lib/Ravada/I18N/en.po, public/js/booking/ldapGroup.component.html, templates/main/machine_access_group.html.ep, templates/main/vm_prepare_base.html.ep
- Fixed:
missing character (l);
deleted <%= '....' %> from html files
- Added new entries to English file (en.po)
=> Bug fix and added translate lines

script/rvd_front, t/mojo/30_grants.t, templates/main/manage_user_password.html.ep
Performs the missing call to change the password from frontend.
* Also test change
fixes #1805
=> Fix change password

script/rvd_front, templates/main/settings_generic_tabs.html.ep, templates/main/vm_hostdev.html.ep
Allows reaching a different tab ie when coming from host devices settings in domain
=> refactor(frontend): set active tab

lib/Ravada/I18N/vi.po
Provide a translation and proofread of Vietnamese translation
Update and proofread the Vietnamese translation for the Remote Virtual Desktops Manager.
Hello, I am a student working on the assignment related to revising and helping documentation on the real-world depository.  I look through different repositories and find this one.  The requirement is straightforward and Vietnamese is my native language so I will give it a try.  I am not a qualified translator but I am a CS student so I can translate the text base on the context within the description.  I hope this can help. I also provide the email contact within the docs if anything cause issues with the text translation.  Have a nice day.
=> Vietnamese translation

lib/Ravada/I18N/en.po, templates/booking/confirmActions.component.html.ep, templates/booking/entryModal.component.html.ep, templates/booking/formEvent.component.html.ep, templates/bootstrap/navigation.html.ep, templates/error/no_ldap.html.ep, templates/main/admin_group.html.ep, templates/main/vm_copy.html.ep, templates/main/vm_options.html.ep, templates/main/vm_pool.html.ep, templates/main/vm_rebase.html.ep, templates/main/vm_rename.html.ep, templates/main/vm_spinoff.html.ep, templates/ng-templates/new_machine_other.html.ep
- Added booking templates to  translations
- Added new entries to English file (en.po)
- Fix long lines for translate(or you need to add spaces to the file en.po)
- Admin menu items are capitalized
=> Remove hardcoded strings  from booking templates

lib/Ravada/Auth/LDAP.pm, lib/Ravada/Auth/SQL.pm, lib/Ravada/Auth/User.pm, lib/Ravada/VM.pm, script/rvd_front, t/front/72_ldap_filter.t, t/lib/Test/Ravada.pm, t/mojo/10_login.t, t/mojo/30_grants.t, t/mojo/40_anonymous.t
Enforce LDAP access restriction
=> Fix access ldap

CHANGELOG.md, lib/Ravada.pm, public/js/ravada.js, templates/main/run_request.html.ep
The very first time it was required to reload to fetch the clone. Wait a few seconds so it can get started properly
=> Fix clone from scratch in frontend

lib/Ravada/Domain.pm, t/mojo/50_utf8.t, t/vm/55_rename.t
=> Fix rename

lib/Ravada/Domain.pm, lib/Ravada/VM.pm, t/lib/Test/Ravada.pm, t/vm/92_ports.t
fix(ports): clean duplicated ports
=> Fix open ports leftovers

lib/Ravada/I18N/de.po
Updated the German language file. Fixed some false translations and added all of the messages.pot
=> i18n: German translation

lib/Ravada/Domain.pm, lib/Ravada/Volume.pm
Fixed crash on remove base machines at caching.
=> refactor: do not store data when cache removed

lib/Ravada/I18N/zh_CN.po
=> Translated Chinese at 100%

lib/Ravada/I18N/my.po
=> add Melayu translation

lib/Ravada/I18N/it.po
Updated it.po
Contribution to https://github.com/UPC/ravada/issues/1836
Last italian strings where in different order comparing to the en.po file, I have fixed that for clarity, and then added the first part of the missing strings (the list is long and needs more work). Hope this can help, have a nice hacktoberfest 🍻
=> Update italian translation

script/rvd_front
=> CSP Headers

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/Void.pm, lib/Ravada/Front.pm, lib/Ravada/VM.pm, templates/main/admin_machines.html.ep, templates/main/run_request.html.ep
=> feat(frontend): Show date and time of last change of state

lib/Ravada.pm, lib/Ravada/Auth/SQL.pm, t/user/20_grants.t, templates/main/settings_machine_tabs_body.html.ep, templates/main/settings_machine_tabs_head.html.ep
=> feat(net): grant open ports

templates/bootstrap/footer.html.ep
=> bug(footer): info actual year

lib/Ravada/I18N/ca.po, lib/Ravada/I18N/en.po, lib/Ravada/I18N/es.po, templates/main/requirements.html.ep
=> feat(requirements): update mac requirements info

lib/Ravada.pm, lib/Ravada/Auth/SQL.pm, script/rvd_front, t/user/20_grants.t, templates/main/manage_user_grants.html.ep, templates/main/run_request.html.ep, templates/main/settings_machine_tabs_head.html.ep
=> feat(volumes): permissions to create volumes

.github/workflows/github-action-test.yml, lib/Ravada.pm, script/rvd_front, t/40_auth_sql.t, t/50_images.t, t/60_user_sql.t, t/65_user_ldap.t, t/front/60_ldap.t, t/kvm/12_vm_kvm.t, t/kvm/n10_nodes.t, t/lib/Test/Ravada.pm, t/mojo/10_login.t, t/request/32_hw_usb.t, t/vm/20_base.t, templates/main/admin_machines.html.ep
=> fix(clone): add some tests

lib/Ravada/Domain/KVM.pm, lib/Ravada/Front/Domain/KVM.pm, public/css/sb-admin.css, public/js/ravada.js, t/request/30_hardware.t, templates/main/manage_machine_edit_cpu.html.ep, templates/main/manage_machine_edit_features.html.ep, templates/main/vm_hardware.html.ep
Change dies, threads, cores and sockets for KVM
=> Manage CPU topology

public/js/ravada.js, script/rvd_front, templates/main/run_request.html.ep
=> fix: improved open ports section on start

etc/repository/iso/ru/astra.yml
=> fix(ISO): Astra Linux URL

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Front/Domain.pm, lib/Ravada/Request.pm, lib/Ravada/VM/Void.pm, public/css/sb-admin.css, public/js/ravada.js, script/rvd_front, t/request/30_hardware_clones.t, t/vm/m20_memory.t, templates/main/manage_machine_apply_clones.html.ep, templates/main/manage_machine_edit.html.ep, templates/main/needs_restart.html.ep, templates/main/settings_machine.html.ep, templates/main/vm_hardware.html.ep, templates/main/vm_hardware_modal_remove.html.ep, templates/main/vm_hardware_new.html.ep
Changes to a base are applied to its clones.
=> Feat: apply clones

etc/fallback.conf, etc/get_fallback.pl
Fixes Chrome spits out warnings about .map files not loading
=> fix: javascript maps

lib/Ravada/Domain.pm, t/kvm/f20_filesystem.t
When the filesystem has been created before or outside Ravada we need to add the information in the database
=> fix: add filesystem info to db

lib/Ravada/Domain.pm, t/vm/55_rename.t
=> fix: rename when failed

CHANGELOG.md, script/rvd_front, t/mojo/30_settings.t
Check there is a select option entry in the settings frontend for all the translated files
=> test: translations

CHANGELOG.md, lib/Ravada.pm, lib/Ravada/Domain/KVM.pm, t/request/30_hardware_clones.t
Volumes file name was reset when applying changes to the clones
=> Fix: clones disk

lib/Ravada/Domain/KVM.pm, t/request/30_hardware.t
Fixes problem changing CPU topology for some machines created with older releases.
issue #1837
=> Fix cpu topology

lib/Ravada/Domain/KVM.pm, t/nodes/60_hardware.t, t/request/30_hardware.t
Fixes problem creating new network interface bridged
=> fix: add network bridge

lib/Ravada/Domain.pm, lib/Ravada/VM/KVM.pm, t/kvm/uefi.t
Sets the loader to OVMF_CODE_4M as suggested by @ckk90
=> Fix ovmf for w11

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Request.pm, sql/sqlite/requests.sql, t/30_request.t, t/device/30_pci.t, t/lib/Test/Ravada.pm, t/logs.t, t/nodes/60_hardware.t, t/nodes/80_policy.t, t/request/30_hardware.t, t/vm/10_domain.t, t/vm/22_limits.t, t/vm/92_ports.t, t/vm/p10_pools.t, t/vm/s30_storage.t, t/vm/v10_volatile.t, t/vm/v20_volatile_clones.t
Improved the duplicated requests checks. In some environment some requests could be misplaced as the same.
=> Refactor duplicated requests

lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Domain/Void.pm, lib/Ravada/Front/Domain.pm, lib/Ravada/VM/KVM.pm, t/request/30_hardware_clones.t, t/vm/20_base.t, t/vm/92_ports.t
Keep from adding spice display if removed. Also change settings improved.
=> Fix displays

script/rvd_back
Purge outdated files in nodes, thanks to @dani-sanchez-dorado
=> feat: purge nodes CLI

lib/Ravada/Auth/LDAP.pm, lib/Ravada/Auth/User.pm, public/js/ravada.js, script/rvd_back, script/rvd_front, templates/main/machine_access_ldap.html.ep
Improved the LDAP test thanks to @dani-sanchez-dorado
=> Feat: test ldap

script/rvd_front, templates/main/manage_user_grants.html.ep
removes JS warning when value was undefined
=> refactor: fixed JS warning

dockerfy/utils/remove_all.sh
fix: remove images properly
Issue #1952
=> Fix remove script (#1952)

lib/Ravada/Domain/KVM.pm, t/request/33_hw_cpu.t
When topology was defined, fixes crash when forcing number of CPUs.
Thanks to Susana Martín
=> Fix: change cpu

lib/Ravada.pm
Suport for Debian 12 and fixed Debian 11
=> feat: new URLs for Debian 11 & 12

docs/docs/INSTALL_Rocky9.rst
=> Instructions to Install Ravada on Rocky 9

lib/Ravada/Domain.pm, lib/Ravada/VM/KVM.pm, t/device/40_mediated_device.t
Inserts host devices  before starting for volatile machines.
fixes #1965
=> Fix: volatile mediated

docs/docs/troubleshooting.rst
=> fix(doc): Updated solution on multiples VM with same ip

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Domain/Void.pm, lib/Ravada/Front/Domain/KVM.pm, lib/Ravada/Request.pm, lib/Ravada/VM.pm, lib/Ravada/VM/KVM.pm, public/js/admin.js, public/js/ravada.js, script/rvd_front, t/20_volumes.t, t/kvm/uefi.t, t/mojo/10_login.t, t/request/33_hw_cpu.t, t/vm/10_domain.t, templates/main/manage_machine_edit.html.ep, templates/main/manage_machine_edit_cpu.html.ep, templates/main/needs_restart.html.ep, templates/main/settings_machine_tabs_head.html.ep, templates/main/vm_options.html.ep
Hardware CPU information didn't refresh correctly sometimes. Reported by Susana Martin from UPC
=> Fix refresh hw

lib/Ravada/Domain.pm, lib/Ravada/Domain/KVM.pm, lib/Ravada/Volume.pm, lib/Ravada/Volume/Void.pm, t/20_volumes.t, t/kvm/40_import.t, t/mojo/10_login.t, t/vm/40_volumes.t
When volume files had no extension frontend crashed.
=> fix: allow volumes without extension

lib/Ravada.pm, templates/main/list_bases_ng.html.ep
Auto updates Kali Linux release every year
=> fix: Kali linux per year

lib/Ravada/I18N/en.po, templates/main/requirements.html.ep
In file: lib/Ravada/I18N/en.po
Removed the lines 306 and 307 
Rephrased the lines 2170 and 2171
Also made the changes in the file: templates/main/requirements.html.ep 
closes #1992
=> Updated the changes of pr#1993

lib/Ravada/I18N/de.po
Added more german translations.
Added more german translations to `de.po`
Tags: `localization`, `hacktoberfest`
=> Some more german translations

lib/Ravada.pm, lib/Ravada/Request.pm, t/mojo/10_login.t, t/mojo/20_ws.t, t/request/40_base.t, t/vm/70_clone.t
Properly stop virtual machines before prepare base. Refuse to do if it won't shutdown.
=> fix: lock and shutdown machines before prepare

lib/Ravada/Front/Domain/Void.pm, lib/Ravada/Request.pm, t/mojo/30_settings.t, t/mojo/60_upload.t, t/storage_move.t, t/vm/92_ports.t
Move volume tasks where executed at the same time as hardware changes and clashed. This patch queues these jobs properly.
=> Fix queue move

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/Front.pm, script/rvd_front, t/front/40_list_domains.t, t/mojo/15_list_bases.t, templates/main/admin_machines.html.ep, templates/main/vm_base.html.ep, templates/main/vm_base_policy.html.ep, templates/main/vm_base_public.html.ep, templates/main/vm_rebase.html.ep, templates/main/vm_remove_base.html.ep
Allow the administrator to hide completely a base when unpublishing, even if users have clones. Requested by @jmanelgm
=> Feat: hide clones

README.md
Updated description and links
Improved the description section of the readme. Additionally added OS specific links to the installation section and most commonly used operation links in the operations section.
This problem improves the user friendly-ness of the readme allowing the user to spend less time on the documentation searching for what they want and directing them immediately where they need to go.
=> Improved readme.md

public/css/admin.css, templates/main/admin_machines.html.ep
Do not allow prepare base from volatile clone. Also show is volatile in a badge.
=> refactor(frontend): improved show volatiles

CHANGELOG.md, lib/Ravada/WebSocket.pm, t/mojo/20_ws.t
Fixed problem showing node options thanks to @rajpatel-msstate
=> Fix node options

docs/docs/INSTALL_Ubuntu.rst
=> Order to install database changed

etc/rvd_front.conf.example, script/rvd_front
Shows services health and status
=> Feature status

lib/Ravada.pm, lib/Ravada/Volume.pm, t/lib/Test/Ravada.pm, t/mojo/70_volatile.t, t/mojo/80_check_resources.t, t/vm/20_base.t, t/vm/92_ports.t, t/vm/94_ports_exposed.t
Some testing of expose ports failed because it needed to wait. Reviewed.
=> Test: ports

lib/Ravada/Domain.pm, t/device/40_mediated_device.t
Update stored config when hardware is changed
=> fix: store config when hardware changed

lib/Ravada/Request.pm, script/rvd_back
=> fix: skip duplicated request

t/vm/55_rename.t
Tests the non hd config has been stored after changing or adding hardware.
issue #2069
=> test: start after rename and change hw

lib/Ravada/Domain.pm, t/vm/backup.t
When migrating machines using backup cope with different id vm
=> Fix backup id different

public/js/admin.js
=> fix: search the group name

script/rvd_back
Place all the group members files in a directory and ravada will upload them
=> feat: upload all the group members from a directory

lib/Ravada.pm, lib/Ravada/VM.pm, script/rvd_back
Check for expired or changed TLS certificate
=> Fix tls expired

lib/Ravada/Request.pm, t/lib/Test/Ravada.pm, t/mojo/40_anonymous.t, t/mojo/40_security_policy.t
Clean test groups at the beginning and after finish prove, only when the groups_local table has been created
=> Test: clean groups

script/rvd_front, t/mojo/60_upload.t
Output variable was not stashed when uploading to HTML form
=> fix: upload text file to html

lib/Ravada.pm, lib/Ravada/Domain.pm, t/vm/a10_autostart.t, t/vm/backup.t
Properly sets the virtual machine autostart when restoring. Also it refreshes properly the info from the internal setting
=> Fix backup autostart

lib/Ravada/Auth/LDAP.pm
Fixed wrong storage issued warning for unused var in test.
=> Refactor ldap storage

lib/Ravada/I18N/ca.po, lib/Ravada/I18N/en.po, lib/Ravada/I18N/es.po, script/rvd_front, t/mojo/91_translations.t
Test languages list in frontend and check all are in the lib directory. Also check those in lib are listed.
closes #2133
=> test: added language test and fixed Korean

lib/Ravada.pm, t/lib/Test/Ravada.pm, t/nodes/50_three_nodes.t
Fixed warning in undefined variable and removed locking in tests.
=> Refactor v232 review

templates/main/start.html.ep
Defaults to show plain login when no javascript variable set.
Thanks to @dani-sanchez-dorado
=> Fix login openid

lib/Ravada/Domain.pm, lib/Ravada/Domain/Void.pm, lib/Ravada/Front/Domain.pm, script/rvd_front, t/lib/Test/Ravada.pm, t/vm/n10_nat.t
Easiest RDP connection using an RDP file
=> Feat rdp client file

lib/Ravada/I18N/en.po, templates/main/vm_base_public.html.ep
Public base description message
issue #2152
=> doc: public message

script/rvd_front, t/mojo/10_login.t
Properly tests and renders SPICE, SPICE-TLS and RDP config files.
=> Fix spice tls

lib/Ravada/Domain.pm, t/vm/93_ports_bridge.t, t/vm/d20_disks.t, t/vm/n20_name.t
Performs a -D on the iptables rules stored in the database.
issue #2166
=> fix: clear all stored iptables properly

lib/Ravada/Domain/KVM.pm, t/vm/n10_nat.t
=> Fix wrong ip

templates/main/about.html.ep
issue #2176
Updated link to AGPL
=> fix: change link to AGPL

lib/Ravada.pm, lib/Ravada/Domain.pm, lib/Ravada/WebSocket.pm, public/js/admin.js, templates/ng-templates/new_machine_template.html.ep
Remove when it is only stored in a remote node or both.
=> Refactor: remove virtual machine in node

templates/main/vm_copy.html.ep
Describes the actions executed when a copy of the Virtual Machine is requested.
closes #2152
=> doc: copy description

public/js/ravada.js, script/rvd_front, templates/main/machine_access_ldap.html.ep
Display LDAP search by attribute information
closes #2149
=> refactor: explain LDAP search info

CHANGELOG.md, lib/Ravada.pm, script/rvd_back
Create a default storage on startup
=> Fix default storage

deb/debianize.pl, etc/get_fallback.pl
Runs the get fallback script out of the sources.
=> Fix get fallback

script/rvd_back
Allows remove many LDAP groups from CLI using a wildcard search
=> feat(CLI): remove many ldap groups

lib/Ravada.pm, lib/Ravada/Auth/Group.pm, lib/Ravada/Domain.pm
=> fix: remove duplicates and show only one if any

deb/debianize.pl, etc/get_fallback.pl
Link deb files for identical releases. Get version with perldoc
=> refactor: get version with perldoc, link package for other releases
