- Makefile.PL
- rvd_front.pl
Happy Hacktoberfest!
https://github.com/UPC/ravada/issues/229
`rel_dir` was deprecated in Mojolicious v7.14 and removed totally in 7.31.
Replaced `rel_dir` with `rel_file` in rvd_front.pl, bumped Mojolicious version in Makefile.PL
> rvd_front.pl - rel_dir deprecated

- etc/xml/dsl-i386.xml
- etc/xml/jessie-amd64.xml
- etc/xml/jessie-i386.xml
- etc/xml/trusty-amd64.xml
- etc/xml/trusty-i386.xml
- etc/xml/win10.xml
- etc/xml/win7pro.xml
- etc/xml/win8.1.xml
- etc/xml/windows_10.xml
- etc/xml/windows_12.xml
- etc/xml/windows_7.xml
- etc/xml/windows_8.xml
- etc/xml/windows_xp.xml
- etc/xml/xenial-i386.xml
- etc/xml/xenial64-amd64.xml
- etc/xml/yakkety64-amd64.xml
- etc/xml/zesty-amd64.xml
If Ravada server has Debian or Ubuntu Xenial not supported machine type:
pc-i440fx-xenial or pc-i440fx-yakkety respectively
Fix with pc machine type is Standard PC (i440FX + PIIX, 1996) (alias of pc-i440fx-2.5) supported by both.
List machine supported in your server:
$qemu-system-x86_64 -machine help
> [#390] Fix problems in Debian or Ubuntu 16.04 OS

- lib/Ravada/I18N/en.po
Fixed minor grammatical errors.
- `'s` is not required in sentence `Some of the password's fields are empty`.
- `Shutdown` is a single word.
- `automatically` needs to be followed by a verb. `automatic` is suitable here.
- either write `any virtual machine` or `all virtual machines`. `any virtual machines` is invalid.
https://github.com/UPC/ravada/issues/411
> UPDATE - English translation

- lib/Ravada/I18N/fr.po
Fixing a few typos, normalizing capital letters according to original text.
Some words were misspelled, there were a few corrections to be made on capital letters that didn't match between the translation and the original text.
I also took the liberty to change a few words ("Requirements" => "Prérequis" instead of "Requis", which would be "Required", "contents" => "contenu" instead of "éléments" which would be "elements")
Useful for issue #398
> Improving french translation

- public/js/ravada.js
- rvd_front.pl
- templates/main/run.html.ep
It is misleading as the end user may think it can set
the machine to auto start. It is also enabled only for
password-less domains.
> [#512] use "view" instead of "start"

- templates/main/list_bases2.html.ep
Fix "Create one" link to /admin/machines instead /admin
Link error when you don't have public bases in the message:
"There are no public bases available in this system. Create one."
"Create one" link to / admin and does not exist. I should link to / admin / machines
> [#536] Fix link

- lib/Ravada.pm
Add Ubuntu Mate
The MATE Desktop has a rich history and is the continuation of the GNOME2 desktop.
Ubuntu MATE makes modern computers fast and old computers usable.
[What is Ubuntu MATE?]( https://ubuntu-mate.org/what-is-ubuntu-mate/)
> [#557] Add Ubuntu Mate

- docs/docs/INSTALL_Fedora.rst
Ravada is now in Fedora repo, no need for COPR anymore.
> docs: update installation instructions for Fedora

- lib/Ravada.pm
- lib/Ravada/Auth/SQL.pm
- lib/Ravada/Domain.pm
- lib/Ravada/Front.pm
- lib/Ravada/Front/Domain.pm
- lib/Ravada/VM/KVM.pm
- public/css/admin.css
- public/js/ravada.js
- rvd_front.pl
- t/front/20_create_domain.t
- t/front/40_list_domains.t
- t/user/20_grants.t
- t/user/30_grant_remove.t
- t/user/40_grant_shutdown.t
- templates/bootstrap/navigation.html.ep
- templates/main/admin_machines.html.ep
- templates/main/list_bases_ng.html.ep
- templates/main/settings_machine_tabs_head.html.ep
New Start screens more responsible for end user.
- Machine listing in main screen is dynamic without need to reload
- It shows informative messages about waiting for new machine to start
- Shows errors if request fails
Backend improvements:
- Allow start machines even if prepare and remove base are running in background
> start #797

- templates/bootstrap/footer.html.ep
If version content a dash, for example: 0.3.0-rc2
Issue [#908]
> fix(frontend):broken badge

- templates/main/admin_machines.html.ep
change buttons from type anchor to type button for to do directive ng-disabled correctly
fixes #914
> fix: Buttons disabled on machines permit action

- lib/Ravada/Domain/KVM.pm
- t/kvm/p10_password.t
Fixes #955
Steps to reproduce:
1. Start virtual machine on network that requires password
2. Start the same virtual machine without stopping it first in a network that doesn't require password
3. Check the password is shown on the browser start screen
> Fix #955 spice

- templates/main/list_bases_ng.html.ep
I changed the hardcoded footer in list_bases_ng
Changed the hardcoded footer from 'bootstrap/footer' to $footer
It is needed so in case there's a custom footer template it shows up instead of the default one.
Solves  #960
> #960 - Replaced hardcoded footer with footer variable

- rvd_front.pl
User experience access directly to virtual desktop if only has one machine.
after login, if there is only one virtual machine for that user, just starts the machine right away.
in order to to avoid unnecessary click stages, and to give a better user experience, it's the biggest request we've ever received.
@eagliardi proposes this issue some days ago.
> User experience access directly to virtual desktop if only has one machine

- dockerfy/docker-compose.yml
If there is no tag defined in docker-compose.yml, it look for the _latest_ default tag.
We have only defined a _0.0.2_ tag.
This solves this situation for now. In the future we will add the _latest_ label that points to the latest version.
Issue #1178 
This PR not merge with develop branch yet. Issue #369 is in WIP status.
> fix(docker): latest tag not exist yet

- lib/Ravada/Auth/LDAP.pm
The search_user method is called with the 'field' attribute forced in the login method.  Can't see any reason…  It's not the case in the other uses of search_user.
The default value for the attribute 'field' (used as the search attribute in the LDAP filter) is 'uid', though it can be $CONFIG{ldap}{field} if defined.
The main attribute used by users to authenticate may be different than the uid.
I don't think this responds to nor conflicts with other issues.
> Using the eventual ldap.field configuration option, uid as default

- lib/Ravada.pm
This patch adds the man Kali installer as well as the lighter net installer to the default ISO list.
The regular expression should suffice for the 2020 releases.
> Added Kali 2020 to the default ISO list

- bin/rvd_back.pl
- lib/Ravada/Domain.pm
- lib/Ravada/Domain/KVM.pm
- lib/Ravada/Domain/Void.pm
- lib/Ravada/Front.pm
- lib/Ravada/VM.pm
- t/nodes/10_basic.t
Before we set internal startup. If a machine is in
two nodes it could get started in both nodes.
> fix(backend): makes ravada handle auto startup

- templates/bootstrap/user_settings.html.ep
Change the box that asks for the current password to the first place, it
was the last box.
Copy the same code and paste it in the first place.
It is not a problem, it is only to be more conventional as other websites.
Issue #1351
> refactor: change box position to ask first the current password

- dockerfy/docker-compose.yml
- dockerfy/dockers/back/Dockerfile
Unexposed 5939 teamviewer port
Issue #1328
From @sotiris-bos's issue. The 5939 port is unexposed and doesn't cause conflict with Teamviewer.
> fix(docker): port conflict

- etc/fallback.conf
- package.json
- templates/bootstrap/header.html.ep
- templates/bootstrap/scripts.html.ep
Incompatible use of jquery 3.5.0 version with bootstrap-select 1.13.7 version.
The error is solved upgrading bootstrap-select version to 1.13.15
Fixes #1364
> Update bootstrap-select version

- lib/Ravada/Domain/KVM.pm
- lib/Ravada/Volume/QCOW2.pm
- t/lib/Test/Ravada.pm
- t/vm/40_volumes.t
- t/vm/45_vol_swap.t
Checks the real storage format so it is added to the machine definition as required for the new libvirt release.
Closes issue #1324 and issue #1385
> Fix backingstore

- lib/Ravada/Auth.pm
This fixes https://github.com/UPC/ravada/issues/1377:
When there is LDAP auth configured in the server but SQL users login
there is a warning in the logs:
ERROR: Login failed 'carlos' at
/usr/share/perl5/Ravada/Auth/LDAP.pm line 62.
The user logs in and everything works as expected, this is a cosmetic
problem of noise in the log file.
---
```
|   | LDAP | SQL |                                              |
|---+------+-----+----------------------------------------------|
| 1 | p    | p   | can't happen, if LDAP passes we return early |
| 2 | p    | f   | if LDAP passes we return early               |
| 3 | f    | p   | nothing is printed because SQL passed        |
| 4 | f    | f   | auth error should be printed                 |
```
We had to fix the 4th case, this'll fix it by checking …
> Save LDAP errors in $ldap_err to reduce noise in logs

- dockerfy/docker-compose.yml
- dockerfy/dockers/back/Dockerfile
- dockerfy/dockers/front/Dockerfile
volume /etc/timezone and /etc/localtime mounting disabled and replaced by installing the tzdata package on docker back and front image to facilitate execution on OSX system that does not allow mounting the volume /etc
The timezone can be configured using variable
Ravada integration with OSX systems
> modified docker files for tzdata package compatibility

- docs/docs/INSTALLfromDockers.rst
As per docs is not totally clear that the Git repo must be cloned within `~/src/` directory.
If this is not done admins will face the `No such file or directory` error as per the [Dockers Troubleshoots](https://ravada.readthedocs.io/en/latest/docs/INSTALLfromDockers.html#dockers-troubleshoots)
> [FIX] doc install from dockers

- docs/docs/config_console.rst
Previosly two commands are run; the first enables it for every start; the second start's it.
systemctl has a option at `enable` and `disable` that allows to start or stop it directly without a second command
```bash
$ systemctl --help | grep now                                              
--now               Start or stop unit after enabling or disabling it
```
It simplifies the command the user has to run. one command is easier as two's.
> Simplify the KVM virsh console access command

- lib/Ravada.pm
Moved the creation of indexes to the install procedure. Added also code for removing unnecessary or outdated indexes.
> refactor(install): create and remove indexes

- lib/Ravada.pm
- lib/Ravada/Domain.pm
- lib/Ravada/VM.pm
- lib/Ravada/VM/KVM.pm
- t/kvm/n10_nodes.t
- t/lib/Test/Ravada.pm
- t/nodes/40_storage.t
Two storage pools with the same name may point to different mount points. That raises an error on migrate virtual machine.
> fix(nodes): check different storage pools

- lib/Ravada.pm
- lib/Ravada/Domain.pm
- t/vm/10_domain.t
Shutdowns can be programmed since #1533, but only automatic shutdowns should be removed on startup.
> refactor: clean only automatic shutdowns

- lib/Ravada/Auth/LDAP.pm
- script/rvd_back
- t/65_user_ldap.t
You can now create extended filters
(|(gidNumber=xxx)(gidNumber=xxx)(gidNumber=xxx))
fixes issue #1083 contributed by @jtorilo 
Co-authored-by: Josep Martin <jmartin@epsem.upc.edu>
> Feat(auth): LDAP advanced filters

- docs/docs/nodes.rst
TroubleShooting: libvirt error code: 38, message: End of file while reading data: nc: unix connect failed: No such file or directory
It means you didn’t install libvirt in the node. Fix it this way:
root@node:~# apt get install libvirt-bin
But now, the libvirt-bin package was dropped in release 18.10 ubuntu. The package was split into two parts:
libvirt-daemon-system
libvirt-clients
so instead of libvirt-bin you need install libvirt-daemon-system and libvirt-clients.
> Improve-doc-cluster_1366 

- lib/Ravada/Domain/KVM.pm
- lib/Ravada/VM/KVM.pm
- t/kvm/b10_bridged.t
When reading IP addresses from the virtual machine agent, pick the one that belongs to a bridged network.
> Fix choose correct internal ip

- t/vm/p10_pools.t
Clones should be created.
As are volatile, they should be started
On shutdown, they should be destroyed
In a while, new clones should appear to honor the pool
closes #1535
> test: pools with volatile clones

- lib/Ravada.pm
When installing Ravada, there may be a clashing constraint in the database, remove it to create it with the new definition.
> fix: drop constraint if different

- lib/Ravada/WebSocket.pm
The first time it only shows parents, so it needs to remove
the timestamp to show the clones the second time.
> refactor: make sure second list machines is shown

- lib/Ravada/Auth/LDAP.pm
- lib/Ravada/Auth/User.pm
- t/65_user_ldap.t
When the login field has multiple entries, set always the first one as username
> Fix(auth): several uids

- lib/Ravada/Domain/KVM.pm
- lib/Ravada/Front/Domain/KVM.pm
Libvirt from Bionic Ubuntu 18.04 fails because the CPU definition can be empty
> fix: cpu detection in bionic libvirt

- lib/Ravada/VM.pm
- t/20_volumes.t
- t/vm/05_open.t
- default backing format is now qcow2
- search for which in /bin and /usr/bin
> refactor: changes for Ubuntu Jammy 22.04

- lib/Ravada/I18N/ar.po
- lib/Ravada/I18N/ca-valencia.po
- lib/Ravada/I18N/ca.po
- lib/Ravada/I18N/de.po
- lib/Ravada/I18N/en.po
- lib/Ravada/I18N/es.po
- lib/Ravada/I18N/eu.po
- lib/Ravada/I18N/fr.po
- lib/Ravada/I18N/gl.po
- lib/Ravada/I18N/he.po
- lib/Ravada/I18N/id.po
- lib/Ravada/I18N/it.po
- lib/Ravada/I18N/ja.po
- lib/Ravada/I18N/ko.po
- lib/Ravada/I18N/messages.pot
- lib/Ravada/I18N/nb_NO.po
- lib/Ravada/I18N/pt.po
- lib/Ravada/I18N/ru.po
- lib/Ravada/I18N/tr.po
- lib/Ravada/I18N/zh_CN.po
Updated all the translations to leverage hibernate instead of hybernate to maintain consistency. 
Bring consistency in the documentation
#1811
> Consistency naming for Hybernate to Hibernate in translations

- lib/Ravada.pm
- lib/Ravada/Front/Domain/KVM.pm
- lib/Ravada/VM.pm
- lib/Ravada/VM/Void.pm
- script/rvd_front
- t/lib/Test/Ravada.pm
- t/mojo/50_utf8.t
- t/user/utf.t
Clones names had de uid instead the username when user had dots. Reported by Pep Bartrolí from UPC.
Also we improved the transform into ascii when possible.
> Fix clone name

- public/js/ravada.js
Some times when logging out the session may be kept alive because web services reconnected. Do not perform this action on close from now on.
> fix(frontend): do not reconnect web services for proper logout

- lib/Ravada.pm
- lib/Ravada/Request.pm
- lib/Ravada/VM/KVM.pm
- lib/Ravada/Volume.pm
- t/lib/Test/Ravada.pm
- t/mojo/50_utf8.t
Test removal that failed sometimes for bases because two requests run at the same time. Also lists may fail when machine was just removed.
> properly check and remove machines with UTF names

- templates/main/manage_machine_edit_features.html.ep
Features update crashed because the translated values where sent
> fix: set original non-translated value

- lib/Ravada/VM/KVM.pm
Before we creashed but sometimes hash URLs change and we must allow the admin a successfull download anyway
> refactor(isos): warn if hash can not be downloaded

- lib/Ravada/Domain/KVM.pm
- t/request/30_hardware.t
Properly test the empty cpu model thanks to Susana Aguilar
> fix: correctly change topology when no previous model

- etc/rvd_front.conf.example
- lib/Ravada.pm
- lib/Ravada/VM/KVM.pm
- t/lib/Test/Ravada.pm
Properly show an error message when there is no internet available. Also keep installing downloading process in the background for a faster startup.
> Fix: update isos when no internet available

- lib/Ravada.pm
- lib/Ravada/Auth/LDAP.pm
- lib/Ravada/Auth/SSO.pm
- lib/Ravada/Front.pm
- script/rvd_back
- script/rvd_front
- t/02_config.t
- t/vm/20_base.t
This removes warnings on the JS console when it tried to load LDAP data.
> refactor: do not load LDAP when no configured

- lib/Ravada.pm
- lib/Ravada/VM.pm
- t/vm/82_route.t
Properly set display IP from system routes and addresses
> Fix display ip

- docs/docs/troubleshooting.rst
When creating multiple clones from one VM, the same IP was assigned due to an error with the netplan and dhcp configuration.
> doc: solved dhcp trouble for VM clones

- lib/Ravada/Domain/KVM.pm
- lib/Ravada/Volume.pm
- t/kvm/40_import.t
When the virtual machine defined the volumes by name, the import crashed.
> Fix import volume referenced by name

- lib/Ravada/Domain.pm
- t/lib/Test/Ravada.pm
- t/vm/20_base.t
- t/vm/s30_storage.t
Free storage always checked on default pool even another one was requested.
> fix: properly check free storage size

- lib/Ravada/I18N/ko.po
Added the Korean translations to the untranslated string
Fixes #1988
> Update Korean Translation

- lib/Ravada/VM.pm
- lib/Ravada/VM/KVM.pm
- lib/Ravada/VM/Void.pm
- t/lib/Test/Ravada.pm
- t/storage_list_unused.t
- t/vm/s30_storage.t
When there is a duplicated storage pool linked to another one, it wrongly detects unused volumes
> Fix pool duplicated

- lib/Ravada.pm
- lib/Ravada/Domain/KVM.pm
- lib/Ravada/Domain/Void.pm
- lib/Ravada/I18N/it.po
- lib/Ravada/Request.pm
- lib/Ravada/VM.pm
- lib/Ravada/VM/KVM.pm
- lib/Ravada/VM/Void.pm
- public/js/ravada.js
- t/lib/Test/Ravada.pm
- t/storage_move.t
- templates/main/manage_machine_edit_disk.html.ep
- templates/main/needs_shutdown.html.ep
- templates/main/vm_hardware.html.ep
- templates/main/vm_hardware_modal_change_pool.html.ep
Move volume file to another storage
> Feat: move volume

- lib/Ravada.pm
When there are more  than one interfaces connected to the same network, installation tries to add it and fails.
> fix: do not insert network twice

- MANIFEST
- lib/Ravada/WebSocket.pm
- script/rvd_front
- t/device/10_templates.t
- templates/main/admin_machines.html.ep
- templates/main/node_hostdev.html.ep
- templates/main/vm_hostdev.html.ep
Show the virtual machine name that has locked the host devices.
> Feat: device domain

- lib/Ravada.pm
- lib/Ravada/Request.pm
- t/device/10_templates.t
- t/lib/Test/Ravada.pm
- t/mojo/70_volatile.t
- t/user/35_share.t
Fixed problem with shared users and open ports.
Closes #2030
> Fix shared ports

- public/js/admin.js
- templates/main/admin_machines.html.ep
In admin machines, when removing from public, the show clones checkbox works now
> fix: show clones checkbox was not working

- CHANGELOG.md
- lib/Ravada.pm
- lib/Ravada/Domain.pm
- lib/Ravada/VM/Void.pm
- lib/Ravada/WebSocket.pm
- t/mojo/20_ws.t
- t/mojo/80_check_resources.t
Disable RAM check before start virtual machine
> Feat: config ram check

- lib/Ravada.pm
Mint 18 deleted because didn't work
> Mint 18.02 deleted

- lib/Ravada/I18N/en.po
Fix the string, it gets updated on the master but not on the develop branch. en.po of develop branch is the base language in Weblate, for this reason this string is not translated. This commit solve this issue.
#2048
> Update en.po last string

- .github/workflows/github-action-test.yml
- lib/Ravada.pm
- lib/Ravada/VM.pm
- lib/Ravada/VM/KVM.pm
- t/lib/Test/Ravada.pm
Keep nodes down for a time to not try to open it even if down
> Refactor node timeout

- lib/Ravada.pm
- lib/Ravada/Domain.pm
- lib/Ravada/Domain/KVM.pm
- lib/Ravada/Domain/Void.pm
- lib/Ravada/HostDevice/Templates.pm
- lib/Ravada/VM.pm
- lib/Ravada/VM/Void.pm
- t/device/00_host_device.t
- t/device/10_templates.t
- t/device/40_mediated_device.t
- templates/main/run_request.html.ep
Configuration without host devices is backed up and restored upon shutdown
> Fix restore config without host devices

- lib/Ravada/Domain/KVM.pm
- t/request/30_hardware.t
- templates/main/manage_machine_edit_video.html.ep
Properly remove all other video devices when creating a video of type none
> Fix add video none

- lib/Ravada.pm
- lib/Ravada/Domain.pm
- lib/Ravada/Front.pm
- lib/Ravada/HostDevice.pm
- lib/Ravada/Request.pm
- lib/Ravada/VM.pm
- lib/Ravada/VM/KVM.pm
- lib/Ravada/VM/Void.pm
- public/css/sb-admin.css
- public/js/ravada.js
- t/device/40_mediated_device.t
- t/lib/Test/Ravada.pm
- t/nodes/10_basic.t
- templates/bootstrap/requests.html.ep
Keep the base as not available while synchronizing the volumes in non shared storage nodes.
> Refactor set base in node

- lib/Ravada/HostDevice/Templates.pm
- t/device/40_mediated_device.t
> feat: new template mediated dev no display

- dockerfy/docker-compose.yml
- dockerfy/dockers/back/Dockerfile
- dockerfy/utils/remove_all.sh
These changes fix issues with Docker deployment.
**We recommend deploying Docker only for testing or development environments.**
- changed docker mysql to mariadb
- added **ovmf** package installation to docker backend
- updated removal script to clean up
Solve this problem with database: 
```
root@8fbc7e8dd185:/ravada# PERL5LIB=./lib ./script/rvd_back --add-user admin
INFO: creating table groups_local
DBD::mysql::db do failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(0),  name char(255) NOT NULL )' at line 1 at lib/Ravada.pm line 2488
```
And this ovmf error:
```
libvirt error code: 9, message: operation failed: unable to find any master var
store for loader: /usr/share/OVMF/OVMF_CODE_4M.fd
```
> Fix/2078 docker: Some bugs in docker deploy

- lib/Ravada/Domain.pm
- lib/Ravada/Domain/KVM.pm
- public/js/ravada.js
- t/kvm/s10_spice.t
- t/nodes/60_hardware.t
- t/vm/20_base.t
Remove all spice and related devices required for recent libvirt.
> Fix spice remove

- lib/Ravada/Front.pm
- templates/ng-templates/new_machine_template.html.ep
New machines can not be created with negative swap values
Fixes issue #1831
> fix: new machines can not be created with negative swap values
